# 🤖 **Scikit-Learn**

## 📚 What is Scikit-Learn?

[**Scikit-Learn**](https://scikit-learn.org/stable/user_guide.html) (or sklearn) is a **Python library for Machine Learning**. It's a toolbox with pre-built algorithms to solve problems.

**Uses these libraries:**
- 🔢 NumPy - for numbers and arrays
- 🔬 SciPy - for scientific computing
- 📊 Matplotlib - for visualizations

---

### 🍳 Think of it Like Cooking:

- **NumPy** = Raw ingredients (flour, sugar, eggs)
- **Pandas** = Preparing ingredients (washing, cutting, measuring)
- **Scikit-Learn** = Recipe book (ready-made formulas to follow)
- **Matplotlib** = Plating (showing your final dish nicely)

<img src='..\assets\images\6-step-ml-framework.png'
style='background-color: white; padding: 20px;'>

## ✨ What Problems Does Scikit-Learn Solve?

**Real World Applications:**

| 🎯 Problem | 📌 What It Does | 💡 Example |
|:----------:|:-------------|:-------------|
| **Classification** | Predict categories/classes | Email spam detection (spam or not spam) |
| **Regression** | Predict numbers/values | House price prediction |
| **Clustering** | Group similar items together | Customer segmentation |
| **Data Preprocessing** | Clean and prepare data | Handle missing values, scale features |
| **Feature Selection** | Choose important features | Pick best predictors from many options |
| **Model Evaluation** | Measure how good your model is | Check accuracy, precision, recall |

---

[**Refresh the basics (ML)**](..\basic\basic_theory.ipynb)

## **Workflow**

<img src='..\assets\images\sklearn-workflow-title.png' style='background-color: white; padding: 20px;'>

# **Intoduction to Scikit-Learn (sklearn)**

What we are going to cover:

0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
2. Choose the right estimator/algorithm for our problem
3. Fit the model/algorithm and use it to make pridictions on our data
4. Eavaluating a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together!

In [1]:
# Let's listify the contents
what_were_covering = [
    "0. An end-to-end Scikit-Learn workflow",
    "1. Getting the data ready",
    "2. Choose the right estimator/algorithm for our problem",
    "3. Fit the model/algorithm and use it to make pridictions on our data",
    "4. Eavaluating a model",
    "5. Improve a model",
    "6. Save and load a trained model",
    "7. Putting it all together!"
]

In [2]:
what_were_covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm for our problem',
 '3. Fit the model/algorithm and use it to make pridictions on our data',
 '4. Eavaluating a model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all together!']

In [3]:
# Standard imports

import numpy as np  # noqa: F401
import pandas as pd  # noqa: F401
import matplotlib.pyplot as plt  # noqa: F401
%matplotlib inline

## **0. An end-to-end Scikit-Learn Workflow**

In [4]:
# 1. Get the data ready

import pandas as pd  # noqa: F811
heart_disease = pd.read_csv(r'..\Datasets\heart-disease.csv')
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
# Create X (Feature matrix)
X = heart_disease.drop('target', axis=1)

# Create Y (Label matrix/ Labels)
y = heart_disease['target']

# Expected output (classification)

**🔘 MICROWAVE ANALOGY:**
─────────────────────────────────────────
```list
Before you use it, you SET:
├─ Temperature? (high, medium, low)
├─ Time? (30 seconds, 2 minutes, 5 minutes?)
└─ Power level? (50%, 75%, 100%?)
```

**THESE ARE HYPERPARAMETERS! ← You decide them!**

```hirarchy
Then you:
└─ Press START → Microwave heats your food
                 (it LEARNS how to cook it best)
```

---

🤖 **Machine Learning:**
─────────────────────────────────────────
```text
YOU choose (Hyperparameters):
├─ How many trees? (10? 100? 500?)
├─ How deep trees? (shallow? deep?)
└─ Other settings...
```

Then the MODEL LEARNS (from your data)

In [6]:
## **2. Choose the right model and hyperparameters**

from sklearn.ensemble import RandomForestClassifier

# Creates a new ML model and naming it clf (classifier)
clf = RandomForestClassifier()

# We'll Keep the default hyperparameters
clf.get_params()

# clf.get_params()
# ↑ Shows ALL those default hyperparameters

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

HYPERPARAMETERS:
───────────────────────────────────────
- Settings you choose BEFORE training
- They control HOW the model learns
- You set them, the model uses them

---

`clf` is a MODEL ← An untrained RandomForest

- Has hyperparameters set to defaults
- Ready to be trained
- Waiting for data
- Can't predict yet (needs training first!)

In [7]:
# 3. Fit the model to the training data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Randomly splits your data into 2 groups:
# 80% to train the model,
# 20% to test if it actually learned (0.2)

```text
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
│        │        │        │                         │  │  └─ 20% for testing
│        │        │        │                         │  └─ targets
│        │        │        │                         └─ features
│        │        │        └─ Testing targets (answers for checking)
│        │        └─ Training targets (answers for learning)
│        └─ Testing features (unseen data to test on)
└─ Training features (data to learn from)
```

In [8]:
clf.fit(X_train, y_train)

# Trains the model by showing it the features (X_train)
# and their correct answers (y_train),
# so it learns the patterns

RandomForestClassifier()

In [9]:
X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
127,67,0,2,152,277,0,1,172,0,0.0,2,1,2
184,50,1,0,150,243,0,0,128,0,2.6,1,0,3
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2
272,67,1,0,120,237,0,1,71,0,1.0,1,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2

In [10]:
X_test.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
101,59,1,3,178,270,0,0,145,0,4.2,0,0,3
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2

In [11]:
# Makes predictions on NEW, UNSEEN data

y_preds = clf.predict(X_test)
y_preds

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [12]:
y_test

298    0
3      1
75     1
101    1
65     1
      ..
191    0
291    0
183    0
38     1
24     1
Name: target, Length: 61, dtype: int64

In [13]:
# 4. Evaluate the model on the training data and test data

# Training Accuracy
clf.score(X_train, y_train)

1.0

**Means:** Model got 100% correct on the data it learned from!

In [14]:
clf.score(X_test, y_test)

0.7049180327868853

**Means:** Model got 86.88% correct on NEW data it never saw!

```python
clf.score(X_test, y_test)
│   │     │       │
│   │     │       └─ Actual answers (truth)
│   │     └─ Features to predict on
│   └─ "Calculate accuracy" command
└─ Your model
```

**Process:**
1. Model predicts on X_test
2. Compares predictions to y_test (truth)
3. Counts how many it got right
4. Returns: (correct / total) as decimal

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))
# What it does: 
# Gives you a FULL report with multiple metrics

              precision    recall  f1-score   support

           0       0.66      0.70      0.68        27
           1       0.75      0.71      0.73        34

    accuracy                           0.70        61
   macro avg       0.70      0.70      0.70        61
weighted avg       0.71      0.70      0.71        61

In [16]:
confusion_matrix(y_test, y_preds)
# What it does:
# Shows WHERE your model is making mistakes

array([[19,  8],
       [10, 24]])

CONFUSION MATRIX:
═══════════════════════════════════════════════════════
```text
                   PREDICTED
                 No Disease  Disease
               ┌──────────┬──────────┐
        No (0) │    25    │    3     │  ← Actually No Disease
ACTUAL         ├──────────┼──────────┤
   Disease (1) │    5     │    28    │  ← Actually Disease
               └──────────┴──────────┘
```

**Reading it:**
- Top-left (25): Correctly predicted "No Disease" ✓
- Top-right (3): Said "Disease" but was actually "No Disease" ✗
- Bottom-left (5): Said "No Disease" but was actually "Disease" ✗
- Bottom-right (28): Correctly predicted "Disease" ✓

In [17]:
accuracy_score(y_test, y_preds)
# What it does:
# Calculates accuracy (same as .score() but more flexible)

0.7049180327868853

In [18]:
# 5. Improve a model
# Try different amount of n_estimators (hyperparameter)

# np.random.seed(42)
# for i in range(10, 100, 10):
#     print(f"Trying model with {i} estimators...")
#     clf = RandomForestClassifier(n_estimators=i)
#     clf.fit(X_train, y_train)
#     print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100:2f} %")
#     print()

In [19]:
# 6. Save the model and load it 
import pickle

pickle.dump(clf, open("random_forest_model.pkl", "wb"))

# .pkl = Python Pickle file
# It SAVES your trained model to a file
# so you can reload it later without retraining

```text
pickle.dump(clf, open("random_forest_model.pkl", "wb"))

│      │    │    │
│      │    │    └─ Create file, write binary
│      │    └─ Your trained model
│      └─ Save to file command
└─ Import pickle library

RESULT: Model saved! Can use forever! 💾
```

In [20]:
# Loads your saved trained model from the file back into memory.
loaded_model = pickle.load(open('random_forest_model.pkl', 'rb'))

# Tests the loaded model to verify it works and shows its accuracy
loaded_model.score(X_test, y_test)

0.7049180327868853

In [21]:
what_were_covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm for our problem',
 '3. Fit the model/algorithm and use it to make pridictions on our data',
 '4. Eavaluating a model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all together!']

### **Summary**

In [22]:
# Importing the modules
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt  # noqa: F401, F811
import numpy as np  # noqa: F401, F811
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 
import pickle

# 0. Loading the data
heart_disease = pd.read_csv(r'..\Datasets\heart-disease.csv')

# 1. Getting the data ready
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# 2. Choose the model and hyperparameters
# from sklearn.ensemble import RandomTreesEmbedding
clf = RandomForestClassifier()
clf.get_params()
# 3. Splitting the data into training data and testing data
# from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 4. Fit the model with training data
clf.fit(X_train, y_train)

# 5. Evaluate the model on the training data and test data
## Testing on training data
y_preds = clf.predict(X_test)
clf.score(X_train, y_train)

## Testing on testing data
clf.score(X_test, y_test)

## Classification report 
print("Classification report: \n")
print(classification_report(y_test, y_preds))
print()

## Confusion matrix
print("Confusion matrix: \n")
print(confusion_matrix(y_test, y_preds))
print()

## Accuracy score
print("Accuracy score: ")
print(accuracy_score(y_true=y_test, y_pred=y_preds), "\n")

# 6. Improve a model
print("Improving model: ")
clf = RandomForestClassifier(n_estimators=90)  # trying out different params values
clf.fit(X_train, y_train)
y_preds = clf.predict(X_test)

clf.score(X_test, y_test)
print("Classification report: \n")
print(classification_report(y_test, y_preds))
print()
print("Confusion matrix: \n")
print(confusion_matrix(y_test, y_preds))
print()
print("Accuracy Score \n")
print(accuracy_score(y_true=y_test, y_pred=y_preds))
print()

# 6. Save the model and reload it for future use
print("Saving the model...")
pickle.dump(clf, open("random_forest_model.pkl", "wb"))

print("Loading the model...")
pickle.load(open("random_forest_model.pkl", "rb"))
print("Voila!!! Done...")

Classification report:

              precision    recall  f1-score   support

           0       0.76      0.89      0.82        28
           1       0.89      0.76      0.82        33

    accuracy                           0.82        61
   macro avg       0.83      0.83      0.82        61
weighted avg       0.83      0.82      0.82        61


Confusion matrix:

[[25  3]
 [ 8 25]]

Accuracy score:
0.819672131147541

Improving model:
Classification report:

              precision    recall  f1-score   support

           0       0.73      0.86      0.79        28
           1       0.86      0.73      0.79        33

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.80      0.79      0.79        61


Confusion matrix:

[[24  4]
 [ 9 24]]

Accuracy Score

0.7868852459016393

Saving the model...
Loading the model...
Voila!!! Done...

#### **Warning Section**

In [23]:
# import warnings
# warnings.filterwarnings("ignore")  # use "default" -> Will show warnings then 

# Hides all warning messages
# Makes output cleaner
# Code still runs normally
# Use when you know what you are doing

In [24]:
import sklearn  # noqa: F811
sklearn.show_versions()

System:
    python: 3.14.2 | packaged by Anaconda, Inc. | (main, Dec 19 2025, 11:44:48) [MSC v.1929 64 bit (AMD64)]
executable: d:\Eakem\Learning ML and DS\Learning ML\env\python.exe
   machine: Windows-11-10.0.26200-SP0

Python dependencies:
      sklearn: 1.8.0
          pip: 26.0.1
   setuptools: 80.10.2
        numpy: 2.4.2
        scipy: 1.17.0
       Cython: None
       pandas: 3.0.0
   matplotlib: 3.10.8
       joblib: 1.5.3
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: mkl
    num_threads: 8
         prefix: mkl_rt
       filepath: D:\Eakem\Learning ML and DS\Learning ML\env\Library\bin\mkl_rt.2.dll
        version: 2025.0-Product
threading_layer: intel

       user_api: openmp
   internal_api: openmp
    num_threads: 16
         prefix: libiomp
       filepath: D:\Eakem\Learning ML and DS\Learning ML\env\Library\bin\libiomp5md.dll
        version: None

       user_api: openmp
   internal_api: openmp
    num_threads: 16
         prefix: vcomp
       filepath: D:\Eakem\Learning ML and DS\Learning ML\env\vcomp140.dll
        version: None

#### **Conda Workflow (Miniconda, Beginner Friendly)**

Use this quick guide when maintaining your Python environment.

**What each update command does**
- `conda update conda` updates the Conda tool itself (best done in `base`).
- `conda update package_name` updates one package in your active environment.
- `conda update --all` updates all packages in your active environment.

**1. Start (update Conda tool)**

```bash
conda env list
conda activate base
conda update conda
```

**2. Move to your project environment**

```bash
conda activate your_env_name
```

**3. Search and check a package**

```bash
conda search package_name
conda search package_name --info
conda list package_name
```

**4. Update one specific package**

```bash
conda update package_name
# Example
conda update scikit-learn
```

**5. Update all packages in this environment**

```bash
conda update --all
```

**6. Uninstall a package**

```bash
conda remove package_name
# Example
conda remove scikit-learn
```

**7. Verify installed versions**

```bash
conda list
```

**Safe tip before big updates**

```bash
conda create -n your_env_name_backup --clone your_env_name
```

**Miniconda note**
- If you use Miniconda, you usually do not need `conda update anaconda`.

# **Workflow in detail**

## **1. Getting our data ready to be used with machine learning**

**Three main things we need to do:**

1. Split the data into features and labels (Usually `X` & `y`)
2. Filling (aslo called imputing) or disregarding missing values
3. Converting non-numerical values to numerical values (also called feature encoding)

In [25]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [26]:
X = heart_disease.drop('target', axis=1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [27]:
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [28]:
# Split the data into training and test sets 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

In [29]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [30]:
X.shape

(303, 13)

In [31]:
X.shape[0] * 0.8

242.4

In [32]:
242 + 61

303

In [33]:
len(heart_disease)

303

### **1.1 Make sure it's all numerical**

In [34]:
car_sales = pd.read_csv(r"..\Datasets\car-sales-extended.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [35]:
car_sales['Make'].value_counts()

Make
Toyota    398
Honda     304
Nissan    198
BMW       100
Name: count, dtype: int64

In [36]:
car_sales['Colour'].value_counts()

Colour
White    407
Blue     321
Black     99
Red       94
Green     79
Name: count, dtype: int64

In [37]:
car_sales["Doors"].value_counts()

Doors
4    856
5     79
3     65
Name: count, dtype: int64

In [38]:
len(car_sales)

1000

In [39]:
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price            int64
dtype: object

In [40]:
# Split the data into X and y

X = car_sales.drop('Price', axis=1)
y = car_sales['Price']

# Split into training and test 
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

In [41]:
# Build a machine learning model

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor() 
# model.fit(X_train, y_train) 
# model.score(X_test, y_test) 

# Important: RandomForestRegressor needs numeric inputs only.
# In this dataset, 'Make' and 'Colour' are text (categorical values),
# so model.fit(...) will raise an error.

In [42]:
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [43]:
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

# Think like -> Here is the plan
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder="passthrough")
# Create a step called one_hot,
# use the OneHotEncoder tool,
# and apply it to Make, Colour, and Doors.
# remainder="passthrough" -> Keep any unmentioned columns as they are

# Think like -> Now apply the plan to the data
# Learn the categories from X, then immediately convert X into numbers
transformed_X = transformer.fit_transform(X)
transformed_X

# OneHotEncoder:
# It converts text categories into numbers that ML models can understand.

# ColumnTransformer:
# It lets you apply different preprocessing to different columns in one organized step.
# chooses which columns should get that conversion

# Together:
# OneHotEncoder = the actual converter (text -> numeric)
# ColumnTransformer = the manager that decides which columns get that converter

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 13))

### Understanding This Categorical Encoding Step

This is a **data preprocessing** step called **categorical encoding**.
The exact method being used here is **one-hot encoding**.

This cell is doing **two connected jobs**:

1. Build a **plan** for which columns should be converted.
2. Apply that plan to turn the data into **model-ready numbers**.

---

### The Big Idea

Your model can work with numbers, but not with text labels like:

- `Honda`
- `White`
- `Toyota`

So this cell acts like a **translator**.
It takes category labels and turns them into numeric columns the model can understand.

---

### Step-by-Step View

**Step 1: Pick the categorical columns**

These are the columns that contain labels rather than plain numeric measurements:

- `Make`
- `Colour`
- `Doors`

**Step 2: Create the converter**

`OneHotEncoder()` is the tool that turns each category into `0` and `1` columns.

**Step 3: Create the plan**

`ColumnTransformer(...)` is like a manager. It decides:

- which tool to use
- which columns should get that tool
- which columns should be left alone

**Step 4: Apply the plan**

`fit_transform(X)` means:

- `fit` = learn the possible categories from `X`
- `transform` = convert `X` using what it learned

---

### Visual Flow

```text
Original X
│
├─ Make         -> Honda, BMW, Toyota, Nissan
├─ Colour       -> White, Blue, Red, Green, Black
├─ Doors        -> 3, 4, 5
└─ Odometer     -> already numeric

ColumnTransformer Plan
│
├─ OneHotEncoder -> Make, Colour, Doors
└─ Passthrough   -> Odometer (KM)

Result: transformed_X
│
└─ all columns are now numeric
```

---

### Read This Part Like English

```python
("one_hot", one_hot, categorical_features)
```

| Piece | Meaning |
|---|---|
| `"one_hot"` | Just the name of this step |
| `one_hot` | The actual `OneHotEncoder()` tool |
| `categorical_features` | The columns to encode |

So this means:

> Create a step called `one_hot`, use the encoder tool, and apply it to `Make`, `Colour`, and `Doors`.

And this part:

```python
remainder="passthrough"
```

means:

> Keep any columns not listed above exactly as they are.


---

### Tiny Before and After Example

**Before**

| Make | Colour | Doors | Odometer (KM) |
|---|---|---:|---:|
| Honda | White | 4 | 35431 |

**After encoding**

| Make_BMW | Make_Honda | Make_Nissan | Make_Toyota | Colour_White | Doors_4 | Odometer (KM) |
|---:|---:|---:|---:|---:|---:|---:|
| 0 | 1 | 0 | 0 | 1 | 1 | 35431 |

The exact real output has more columns, but the idea is always the same:

- categories become `0` and `1` columns
- numeric columns can stay as they are

---

### Why Does It Become 13 Columns?

Because **one-hot encoding creates one new column for each category**.

From this dataset:

- `Make` has `4` categories: BMW, Honda, Nissan, Toyota
- `Colour` has `5` categories: Black, Blue, Green, Red, White
- `Doors` has `3` categories: 3, 4, 5
- `Odometer (KM)` is passed through as `1` numeric column

So the total is:

$$4 + 5 + 3 + 1 = 13$$

That is why `transformed_X` ends up with **13 columns**.

### One Real 13-Column Example

If one original row is:

| Make | Colour | Doors | Odometer (KM) |
|---|---|---:|---:|
| Honda | White | 4 | 35431 |

then the expanded 13-column version can look like this:

| Make_BMW | Make_Honda | Make_Nissan | Make_Toyota | Colour_Black | Colour_Blue | Colour_Green | Colour_Red | Colour_White | Doors_3 | Doors_4 | Doors_5 | Odometer (KM) |
|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 1 | 0 | 35431 |

That table is the clearest way to see where the **13 columns** come from:

- `4` columns for `Make`
- `5` columns for `Colour`
- `3` columns for `Doors`
- `1` column for `Odometer (KM)`

---

### Most Important Takeaway

`transformer = ColumnTransformer(...)` means: **Here is the plan.**

`transformed_X = transformer.fit_transform(X)` means: **Now apply the plan to the data.**

- `X` stays as the original table
- `transformed_X` becomes the new numeric version the model can use

In [44]:
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [45]:
pd.DataFrame(transformed_X)

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [46]:
# Another way of doing category encoding
dummies = pd.get_dummies(car_sales[['Make', 'Colour', 'Doors']])
dummies

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,False,True,False,False,False,False,False,False,True
1,5,True,False,False,False,False,True,False,False,False
2,4,False,True,False,False,False,False,False,False,True
3,4,False,False,False,True,False,False,False,False,True
4,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,4,False,False,False,True,True,False,False,False,False
996,3,False,False,True,False,False,False,False,False,True
997,4,False,False,True,False,False,True,False,False,False
998,4,False,True,False,False,False,False,False,False,True
999,4,False,False,False,True,False,True,False,False,False

### Quick Summary of This Cell

This cell uses `pd.get_dummies(...)` to turn the categorical columns into separate yes/no columns.

- `Make`, `Colour`, and `Doors` are expanded into new columns
- `True` means that category is present
- `False` means that category is not present

So this is another way of doing encoding, just with pandas instead of Scikit-Learn.

---

### Which Step Is Better?

- `pd.get_dummies()` is better when you want something simple and easy to understand
- `OneHotEncoder + ColumnTransformer` is better for proper Scikit-Learn workflows because it fits more naturally into ML pipelines

**Short answer:** for learning, `pd.get_dummies()` is easier. For real Scikit-Learn projects, `OneHotEncoder + ColumnTransformer` is the better habit.

In [47]:
# Let's try refit the model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                    y,
                                                    test_size=0.2)

model.fit(X_train, y_train)

RandomForestRegressor()

In [48]:
model.score(X_test, y_test)

0.3235867221569877

### **1.2 What if there were missing values?**

1. Fill them with some value (also known as imputation)
2. Remove the samples with missing data altogether

In [49]:
# Import car sales missing data
car_sales_missing = pd.read_csv(r"..\Datasets\car-sales-extended-missing-data.csv")
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [50]:
car_sales_missing.isna().sum()

# .isna() = 
# Marks every empty cell as True, filled cells as False

# .sum() = 
# Counts how many True (empty cells) are in each column

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [51]:
# Create X and y
X = car_sales_missing.drop('Price', axis=1)
y = car_sales_missing['Price']

In [52]:
# Let's try and cover our data into numbers
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder="passthrough")

transform_X = transformer.fit_transform(X)
transform_X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4000 stored elements and shape (1000, 16)>

⚠️ **Important Note:**

This method works but is **NOT recommended** - always explicitly handle missing values yourself! Modern sklearn's OneHotEncoder treats null values as a separate category automatically, but we don't control or fully understand what it's doing behind the scenes.

In [53]:
car_sales_missing

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [54]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [55]:
car_sales_missing['Doors'].value_counts()

Doors
4.0    811
5.0     75
3.0     64
Name: count, dtype: int64

### **Option 1. Fill missing data with pandas**

In [56]:
car_sales_missing["Doors"].mode()

0    4.0
Name: Doors, dtype: float64

In [57]:
# Impute missing values explicitly (recommended)

# Categorical columns -> fill with "Missing"
car_sales_missing["Make"] = car_sales_missing["Make"].fillna("Missing")
car_sales_missing["Colour"] = car_sales_missing["Colour"].fillna("Missing")

# Numeric column -> fill with mean
car_sales_missing["Odometer (KM)"] = car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean())

# Doors -> fill with most frequent value
car_sales_missing["Doors"] = car_sales_missing["Doors"].fillna(car_sales_missing["Doors"].mode()[0])

In [58]:
# Checkout our dataframe again
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [59]:
# Remove rows with missing Price Values

car_sales_missing.dropna(inplace=True)

# deletes rows that have any missing value (NaN) in the row.
# inplace=True means it changes car_sales_missing directly

In [60]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [61]:
len(car_sales_missing)

950

In [62]:
car_sales_missing

        Make Colour  Odometer (KM)  Doors    Price
0      Honda  White        35431.0    4.0  15323.0
1        BMW   Blue       192714.0    5.0  19943.0
2      Honda  White        84714.0    4.0  28343.0
3     Toyota  White       154365.0    4.0  13434.0
4     Nissan   Blue       181577.0    3.0  14043.0
..       ...    ...            ...    ...      ...
995   Toyota  Black        35820.0    4.0  32042.0
996  Missing  White       155144.0    3.0   5716.0
997   Nissan   Blue        66604.0    4.0  31570.0
998    Honda  White       215883.0    4.0   4001.0
999   Toyota   Blue       248360.0    4.0  12732.0

[950 rows x 5 columns]

In [63]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [64]:
X

        Make Colour  Odometer (KM)  Doors
0      Honda  White        35431.0    4.0
1        BMW   Blue       192714.0    5.0
2      Honda  White        84714.0    4.0
3     Toyota  White       154365.0    4.0
4     Nissan   Blue       181577.0    3.0
..       ...    ...            ...    ...
995   Toyota  Black        35820.0    4.0
996  Missing  White       155144.0    3.0
997   Nissan   Blue        66604.0    4.0
998    Honda  White       215883.0    4.0
999   Toyota   Blue       248360.0    4.0

[950 rows x 4 columns]

In [65]:
# Let's try and cover our data into numbers
# Turn the categories into numbers
# Also scaling the 'Odometer (KM)' column
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
scaling_column = ["Odometer (KM)"]

one_hot = OneHotEncoder()
scaler = StandardScaler()

transformer = ColumnTransformer([
  ("one_hot", one_hot, categorical_features),
  ("Scaler", StandardScaler(), scaling_column)
  ])

transformed_X = transformer.fit_transform(X)
transformed_X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3800 stored elements and shape (950, 15)>

### Feature Scaling, for Now

**What is feature scaling?**

Feature scaling means resizing numeric features so they live on a similar scale.
Here, `Odometer (KM)` has very large values, so we scale it with `StandardScaler()`.

**Why use it here?**

- to preview how scaling is done in a real preprocessing workflow
- to stop large numeric values from dominating in models that care about scale
- to practice applying different preprocessing steps to different columns

**Why only `Odometer (KM)`?**

- `Make`, `Colour`, and `Doors` are handled with one-hot encoding
- `Odometer (KM)` is the main numeric feature, so it is the one being scaled

> In this section, scaling is mainly an **experiment / preview**. We will learn when it is truly needed in upcoming sections.

**Quick note:**
Tree-based models like `RandomForestRegressor` usually do **not** need feature scaling much, but trying it here helps you understand the workflow.

In [66]:
pd.DataFrame(transformed_X.toarray())

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,-1.428286
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.922299
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.691754
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.349175
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.755857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.422472
946,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.360817
947,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.962407
948,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.268558
949,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.753924

### Quick Memory Note

Why did `13` columns become `15`?

| Part | Earlier (`car_sales`) | After cleaning (`car_sales_missing`) |
|---|---:|---:|
| `Make` | 4 | 5 |
| `Colour` | 5 | 6 |
| `Doors` | 3 | 3 |
| `Odometer (KM)` | 1 | 1 |

So the totals are:

- Earlier: $4 + 5 + 3 + 1 = 13$
- After cleaning: $5 + 6 + 3 + 1 = 15$

**Why?**
- `Make` got a new category: `Missing`
- `Colour` got a new category: `Missing`
- `Doors` did **not** get a new category because missing values were filled with the mode
- `Odometer (KM)` is not one-hot encoded; it is passed through as one numeric column

> Easy rule to remember: **OneHotEncoder creates one column for every unique category it sees.**

### **Option 2: Fill missing value with sckit-learn**

In [67]:
car_sales_missing = pd.read_csv(r"..\Datasets\car-sales-extended-missing-data.csv")
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [68]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [69]:
# Drop the rows with no labels
car_sales_missing.dropna(subset=["Price"], inplace=True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [70]:
# Split into X & y
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

# Split data into train and test
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

In [71]:
X_train

       Make Colour  Odometer (KM)  Doors
986   Honda  White        71934.0    4.0
297  Toyota    Red       162665.0    4.0
566   Honda  White        42844.0    4.0
282   Honda  White       195829.0    4.0
109   Honda   Blue       219217.0    4.0
..      ...    ...            ...    ...
106  Toyota    NaN       218803.0    4.0
277     BMW   Blue       245427.0    5.0
904  Toyota  White       196225.0    4.0
450   Honda   Blue       133117.0    NaN
102   Honda    NaN       150582.0    NaN

[760 rows x 4 columns]

In [72]:
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [73]:
# Fill missing values with Scikit-Learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with "missing" and numerical values with mean
cat_imputer = SimpleImputer(strategy="constant",
                            fill_value="missing")
door_imputer = SimpleImputer(strategy="most_frequent")
num_imputer = SimpleImputer(strategy="mean")

# Define Columns
cat_features = ["Make", "Colour"]   # Catagorical features
door_feature = ["Doors"]
num_feature = ["Odometer (KM)"]

# Create an imputer (Something  that fills missing data)
imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", door_imputer, door_feature),
    ("num_imputer", num_imputer, num_feature)
])

# Transform the data
filled_X_train = imputer.fit_transform(X_train)
filled_X_test = imputer.fit_transform(X_test)

# Check Filled X_train
filled_X_train


# Why we first split then inpute why not opposite it would have same time and effort?
# We split first to stop data leakage from the test set into training.
# In a proper workflow, the imputer learns the mean/mode from X_train only.
# Then the test set should use those same learned values, so evaluation stays honest.

array([['Honda', 'White', 4.0, 71934.0],
       ['Toyota', 'Red', 4.0, 162665.0],
       ['Honda', 'White', 4.0, 42844.0],
       ...,
       ['Toyota', 'White', 4.0, 196225.0],
       ['Honda', 'Blue', 4.0, 133117.0],
       ['Honda', 'missing', 4.0, 150582.0]], shape=(760, 4), dtype=object)

In [74]:
# Get our transformed data array's back into DataFrame's
car_sales_filled_train = pd.DataFrame(filled_X_train,
                                columns=["Make", "Colour", "Doors", "Odometer (KM)"])

car_sales_filled_test = pd.DataFrame(filled_X_test,
                                columns=["Make", "Colour", "Doors", "Odometer (KM)"])


# Check missing data in training set
car_sales_filled_train.isna().sum()


# Why creating two datasets why not just a single one and then do train test split?

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [75]:
# Check to see the original... still missing values
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [76]:
# Now let's one hot encode the features with the same code as before 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                  remainder="passthrough")

# Fill train and test values separately
transformed_X_train = transformer.fit_transform(car_sales_filled_train)
transformed_X_test = transformer.fit_transform(car_sales_filled_test)

transformed_X_train.toarray()

# Why again transform the traning sets differently why just normally transform the X?
# In a proper workflow, the encoder learns categories from the training set only.
# Then the test set should be transformed with that same learned mapping.
# This keeps train and test columns aligned and avoids leakage.

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 7.19340e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.62665e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 4.28440e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.96225e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.33117e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.50582e+05]], shape=(760, 15))

In [77]:
pd.DataFrame(transformed_X_train.toarray())

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,71934.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,162665.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,42844.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,195829.0
4,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,219217.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,218803.0
756,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,245427.0
757,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,196225.0
758,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,133117.0
759,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,150582.0

In [78]:
# Now we've transformed X, let's see if we can fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor  # noqa: E402

model = RandomForestRegressor()

# Make sure to use transformed (filled and one-hot encoded X data)
model.fit(transformed_X_train, y_train)
model.score(transformed_X_test, y_test)

0.25366332156443805

In [79]:
# Check length of transformed data (filled and one-hot encoded) -> car_sales_missing
# vs. length of original data

len(transformed_X_train.toarray()) + len(transformed_X_test.toarray()), len(car_sales)

# here less data poor performance

(950, 1000)

### Option 1 vs Option 2 (Quick Guide)

| Part | Option 1: pandas fill | Option 2: scikit-learn transformers |
|---|---|---|
| Main idea | Fill missing values manually with pandas (`fillna`, `dropna`) | Use `SimpleImputer` + `OneHotEncoder` + `ColumnTransformer` |
| Best for | Learning basics, quick experiments, understanding each step | Real ML workflow, cleaner validation, reusable preprocessing |
| Pros | Very easy to read and debug | More robust and scalable for ML projects |
| Cons | Easy to make leakage mistakes if split order is wrong | Slightly more setup and easier to misuse at first |
| Reuse later | Manual repetition needed | Can be reused in pipelines for future data |

---

### Which one is recommended?

- Use **Option 1** when you are learning concepts and want to see each operation clearly.
- Use **Option 2** for proper model training and real projects.

In short: **Option 1 is beginner-friendly, Option 2 is production-friendly.**

---

### Important rule for Option 2

- `fit_transform(...)` on **training** data
- `transform(...)` on **test** data

This avoids data leakage and gives a more honest model score.

---

### Why scores can differ between Option 1 and Option 2

- Option 2 may train on fewer rows after dropping missing target (`Price`) rows.
- Imputed values are estimates, so they can add a little noise.
- Small workflow differences (especially leakage mistakes) can change scores noticeably.

In [80]:
what_were_covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm for our problem',
 '3. Fit the model/algorithm and use it to make pridictions on our data',
 '4. Eavaluating a model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all together!']

## **2. Choosing the right estimator/algorithm for our problem**

**Some things to note:**

- Sklearn refers to machine learning models, algorithms as estimators.
- `Classification problem` - predicting a category (heart disease or not)
  - Sometimes you'll see `clf` (short for classifier) used as a classification estimator
- `Regression problem` - predicting a number (selling price of a car)
- If you're working on a machine learning problem and looking to use Sklearn and not sure what model you should use, refer to the sklearn machine learning map:

<img src = '..\assets\images\sklearn-ml-map.png'>

#### **Quick Note: Algorithm vs Estimator vs Model**

1. **Algorithm** = the learning idea (example: Random Forest).
2. **Estimator** = the sklearn object that implements that idea (example: `RandomForestClassifier()`).
3. **Model** = that estimator after training with `.fit(X, y)`.


> In casual conversation, people often use these words interchangeably.

---

**Example:**

```python
# You have an algorithm (Random Forest) in mind
# You create an estimator from it
clf = RandomForestClassifier(n_estimators=100)

# clf is an ESTIMATOR — knows the rules, seen no data
# You cannot call clf.predict() here — it will throw an error

# You train it
clf.fit(X_train, y_train)

# clf is now a MODEL — it has learned from data
# Now you can predict
clf.predict(X_test)
```

##### **🌳 Decision Tree**

---

## What is it?

A decision tree makes predictions by asking a **series of yes/no questions**,
one after another, until it reaches a final answer.

---

## Real Life First

```
Should I carry an umbrella?

Is it cloudy?
├── NO  → Don't carry umbrella 🌤️
└── YES → Is rain forecasted?
               ├── NO  → Don't carry umbrella 🌥️
               └── YES → Carry umbrella ☂️
```

---

## In ML (Heart Disease Example)

```
Does this patient have heart disease?

Is age > 55?
├── NO  → Mostly healthy 🟢
└── YES → Is chest pain type = 3?
               ├── NO  → Mostly healthy 🟢
               └── YES → Likely sick 🔴
```

The tree finds the **best question** at each step by trying every
possible split and measuring which one separates the data most cleanly.

---

## The Vocabulary

```
             [Is age > 55?]          ← ROOT NODE   (first question)
             /             \
          [NO]             [YES]
           |                 |
       [Healthy]   [Is chest pain = 3?]  ← INTERNAL NODE (middle question)
                    /              \
                 [NO]             [YES]
                   |                |
              [Healthy] 🟢      [Sick] 🔴   ← LEAF NODES (final answer)
```

| Term          | Meaning                                      |
|---------------|----------------------------------------------|
| Root Node     | The very first question (best split overall) |
| Internal Node | Any question in the middle                   |
| Leaf Node     | Final answer — no more splitting             |
| Depth         | How many levels of questions the tree has    |

---

## How Does It Pick Questions?

### Purity — the core idea

Think of bags of red and blue balls:

```
Bag A:  50 red, 50 blue  →  Maximum confusion   (IMPURE)
Bag B:  90 red, 10 blue  →  Mostly guessable    (LESS PURE)
Bag C: 100 red,  0 blue  →  Perfect, always know (PURE)
```

**The tree wants to create bags that look like Bag C.**

At every step it asks: *"Which question splits my data into the purest bags?"*

### The measurement — Gini Impurity

| Gini = 0   | Perfectly pure  (all one class)     |
|------------|-------------------------------------|
| Gini = 0.5 | Maximally impure (50/50 split)      |

The tree tries **every possible question on every feature**,
calculates Gini for each split, and picks the one that
**lowers Gini the most**.


---

## For Regression (Predicting Numbers)

Same structure. Same splitting logic.
But the leaf doesn't say "sick/healthy" —
it says the **average value** of all training samples that ended up there.

---

## The Big Problem — Overfitting

A single tree, if grown too deep, **memorizes** the training data.

```python
clf.score(X_train, y_train)  # → 1.0   (100% — memorized)
clf.score(X_test, y_test)    # → 0.85  (drops on new data)
```

The gap between training and test score = **overfitting**.

Like a student who memorizes past exam papers word for word —
then fails when the actual exam has slightly different questions.

> ✅ This is exactly the problem **Random Forest** was invented to solve.

---

## One Line Summary

> A decision tree asks the most useful yes/no question at each step,
> measured by how purely it separates the data,
> until the answer is clear enough to stop.

## 🌲 Random Forest — Intuition

---

### 🌳 Why One Tree Is Not Enough

A single decision tree, grown deep enough, **memorizes** the training data.
It fits perfectly on what it has seen — but struggles on new data.
This is called **overfitting**.

```python
clf.score(X_train, y_train)  # → 1.0   (memorized)
clf.score(X_test, y_test)    # → 0.85  (drops on new data)
```

> **One tree is too opinionated.**
> It saw one version of the data and built one rigid structure.

---

### 🗳️ The Solution — Ask Many Trees

> Don't rely on one tree. Build hundreds of trees and let them **vote**.

This is the same logic as asking many friends for advice.
No single friend is always right — but the **majority opinion** tends to be far more accurate.

---

### 🎲 Where the "Random" Comes From

If all trees trained on the same data → they'd all build the same tree.
Voting 100 identical trees would be pointless.

So Random Forest introduces **two deliberate sources of randomness.**

---

**Randomness 1 — Different Data for Each Tree (Bootstrapping)**

Each tree gets a **random sample** of the training data, with replacement.
The same row can appear multiple times. Some rows won't appear at all.

```
Full data:    [P1, P2, P3, P4, P5, P6, P7, P8, P9, P10]

Tree 1 sees:  [P1, P1, P3, P5, P5, P7, P8, P10, P10, P2]
Tree 2 sees:  [P2, P4, P4, P6, P7, P7, P9,  P1,  P3,  P8]
Tree 3 sees:  [P3, P5, P6, P6, P8, P9, P10, P2,  P4,  P7]
```

Every tree trains on a slightly different version of reality.
So every tree builds a slightly different structure.

#### **Bootstarpping**
- Bootstrapping means: 
  - Make a new dataset by randomly picking rows from your original dataset with replacement.

- “With replacement” means:
  - After you pick a row, you put it back before the next pick.
    - the same row can appear multiple times,
    - some rows might not appear at all.
---

**Randomness 2 — Different Features at Each Split**

At every split, the algorithm doesn't consider **all** features.
It picks a **random subset** — controlled by `max_features='sqrt'`.

```
All features available → [age, cp, chol, thalach, slope, ca, thal ...]
Random subset chosen   → [age, chol, thal]
Best question picked from ONLY those 3
```

No single feature can dominate every tree.

---

### 🗳️ How the Voting Works

**Classification** → majority vote

```
Tree 1  →  Heart Disease ✓
Tree 2  →  Heart Disease ✓
Tree 3  →  No Disease    ✗
Tree 4  →  Heart Disease ✓
Tree 5  →  Heart Disease ✓

Final   →  Heart Disease  (4 out of 5)
```

**Regression** → average of all predictions

```
Tree 1  →  $320,000
Tree 2  →  $305,000
Tree 3  →  $340,000

Final   →  $321,667
```

---

### ✅ Why Overfitting Gets Fixed

Each tree still overfits — but to a **different slice of the data**.

When they vote:
- The **noise cancels out** — each tree's noise is different
- The **signal survives** — real patterns appear in most trees

---

### 🗺️ The Full Picture

```
            Original Training Data
                     ↓
       ┌─────────────┼─────────────┐
       ↓             ↓             ↓
 Random Sample  Random Sample  Random Sample  ...
       ↓             ↓             ↓
     Tree 1        Tree 2        Tree 3        ...
 (rand features)(rand features)(rand features)
       ↓             ↓             ↓
 Prediction 1  Prediction 2  Prediction 3
          ↘         ↓         ↙
             Vote / Average
                  ↓
           Final Prediction
```

---

### ⚙️ Hyperparameters Decoded

| Hyperparameter     | What it controls                                 |
|--------------------|--------------------------------------------------|
| `n_estimators=100` | How many trees to build                          |
| `max_depth`        | How deep each individual tree can grow           |
| `max_features`     | How many features considered at each split       |
| `bootstrap=True`   | Whether to use random sampling w/ replacement    |
| `random_state`     | Fixes randomness so results are reproducible     |

---

### 💡 One Line Summary

> Random Forest builds many decision trees, each trained on slightly different data
> and features, then combines their answers — so individual errors cancel out
> and the final prediction is far more reliable than any single tree.

- **Classifier** → predicts categories → `RandomForestClassifier`
- **Regressor**  → predicts numbers   → `RandomForestRegressor`

### **2.1 Picking a machine learning model for regression problem**

Let's use the [**California Housing Dataset**](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html)

In [81]:
# Get California Housing dataset
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [82]:
print(housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

In [83]:
housing_df = pd.DataFrame(housing['data'], columns=housing['feature_names'])
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [84]:
housing_df['target'] = housing['target']
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [85]:
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [86]:
# Import Algorithm/Estimator
from sklearn.linear_model import Ridge # Algorithm/Estimator
from sklearn.model_selection import train_test_split

# Setup random seed
np.random.seed(42)

# Create the data
X = housing_df.drop("target", axis=1)
y = housing_df['target']  # median house price in $100,000s
 
# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

# Instantiate and fit the model (on training set)
model = Ridge()
# print(model.get_params()) # Checking the hyperparameters

model.fit(X_train, y_train)

# Check the score of the model (on the test set)
model.score(X_test, y_test)

0.5758549611440131

##### What is R² (Coefficient of Determination)?
> Returned by `model.score()` for regression models

---

### 1. The Main Idea

R² answers one question:

> How much better is my model than a very dumb guess?

That dumb guess is:

> Always predict the average of the target values.

---

### 2. Start With the Baseline

Imagine we are predicting house prices.

```text
Actual prices:  $300k   $350k   $400k   $450k
```

First, find the average:

```text
Average = (300 + 350 + 400 + 450) / 4
        = $375k
```

So the baseline prediction is:

```text
For every house, guess $375k
```

This is the reference point R² compares against.

---

### 3. Baseline Errors

Now check how wrong that baseline is.

```text
House 1: actual $300k, guessed $375k  -> error = 75k
House 2: actual $350k, guessed $375k  -> error = 25k
House 3: actual $400k, guessed $375k  -> error = 25k
House 4: actual $450k, guessed $375k  -> error = 75k
```

In R², we square the errors:

```text
(75)^2 + (25)^2 + (25)^2 + (75)^2
= 5625 + 625 + 625 + 5625
= 12500
```

This is the baseline total error.

---

### 4. Model Guesses

Now suppose your model predicts:

```text
House 1 -> $310k
House 2 -> $360k
House 3 -> $395k
House 4 -> $445k
```

Now compute the model's errors:

```text
House 1: actual $300k, predicted $310k  -> error = 10k
House 2: actual $350k, predicted $360k  -> error = 10k
House 3: actual $400k, predicted $395k  -> error = 5k
House 4: actual $450k, predicted $445k  -> error = 5k
```

Square them:

```text
(10)^2 + (10)^2 + (5)^2 + (5)^2
= 100 + 100 + 25 + 25
= 250
```

This is the model's total error.

---

### 5. The Formula

```text
R² = 1 - (model error / baseline error)
```

Plug in the numbers:

```text
R² = 1 - (250 / 12500)
   = 1 - 0.02
   = 0.98
```

Meaning:

> The model explains 98% of the variation in house prices.

---

### 6. How to Read R²

| R² value | Meaning |
|---|---|
| `1.0` | Perfect predictions |
| `0.8` to `0.99` | Very strong model |
| `0.5` to `0.79` | Useful, but not great |
| `0.0` | No better than guessing the average |
| Negative | Worse than guessing the average |

---

### 7. Your Ridge Model Score

Your notebook showed:

```text
R² = 0.5758
```

That means:

1. Your model is better than the baseline.
2. It explains about 57.58% of the variation in the target.
3. About 42.42% is still unexplained.

That unexplained part could come from:

- noise
- missing features
- imperfect model choice
- limited data

---

### 8. R² vs Accuracy

- **For regression:**

```python
model.score(X_test, y_test)
```

returns:

```text
R²
```

- **For classification:**

```python
clf.score(X_test, y_test)
```

returns:

```text
Accuracy = correct predictions / total predictions
```

So both use `.score()`, but they measure different things.

---

### 9. Short Memory Trick

> R² tells me how much better my regression model is than always guessing the average.

If you remember that sentence, the rest becomes much easier.

What if Ridge didn't work or the score didn't fit our needs?

Well, we could always try a different model...

How about we try an ensemble model (an ensemble is combination of smaller models to try and make better predictions than just a single model)?

Sklearn's ensemble models can be found [here](https://scikit-learn.org/stable/modules/ensemble.html)

#### **What is an ensemble model?**

An ensemble model means using many small models together to make one final prediction.

#### **What is Random Forest?**

Random Forest is an ensemble model made of many decision trees.

- Each tree makes a prediction
- All trees vote
- The most common answer becomes the final prediction

#### **Classifier vs Regressor**

- `RandomForestClassifier` -> predicts categories like Yes/No
  
- `RandomForestRegressor` -> predicts numbers like house prices

[Following the Map](..\assets\images\sklearn-ml-map.png)

In [87]:
# # Import Algorithm/Estimator
# from sklearn.svm import SVR # Algorithm/Estimator
# from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import train_test_split

# # Setup random seed
# np.random.seed(42)

# # Create the data
# X = housing_df.drop("target", axis=1)
# y = housing_df['target']  # median house price in $100,000s
 
# # Split the data
# X_train, X_test, y_train, y_test = train_test_split(X,
#                                                     y,
#                                                     test_size=0.2)

# # ✅ SCALE THE DATA (this makes SVR MUCH faster)
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# # Instantiate and fit the model (on training set)
# model = SVR(kernel='linear')
# # print(model.get_params()) # Checking the hyperparameters

# model.fit(X_train_scaled, y_train)

# # Check the score of the model (on the test set)
# model.score(X_test_scaled, y_test)

Took around 20 secs and poor performance Compared to ridge model

> **0.5579332949772317**

- Scaled the values so that model works faster

In [88]:
# # Import Algorithm/Estimator
# from sklearn.svm import SVR # Algorithm/Estimator
# from sklearn.model_selection import train_test_split

# # Setup random seed
# np.random.seed(42)

# # Create the data
# X = housing_df.drop("target", axis=1)
# y = housing_df['target']  # median house price in $100,000s
 
# # Split the data
# X_train, X_test, y_train, y_test = train_test_split(X,
#                                                     y,
#                                                     test_size=0.2)
# # ✅ SCALE THE DATA (this makes SVR MUCH faster)
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# # Instantiate and fit the model (on training set)
# model = SVR(kernel='rbf')
# # print(model.get_params()) # Checking the hyperparameters

# model.fit(X_train_scaled, y_train)

# # Check the score of the model (on the test set)
# model.score(X_test_scaled, y_test)

Took 12 secs and better performace than the Ridge model

> 0.7275628923016775

- Scaled the values so that model works faster

In [89]:
#  Import the RandomForestRegressor model class from the ensemble module
from sklearn.ensemble import RandomForestRegressor # Algorithm/Estimator
from sklearn.model_selection import train_test_split

# Setup random seed
np.random.seed(42)

# Create the data
X = housing_df.drop("target", axis=1)
y = housing_df['target']  # median house price in $100,000s
 
# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

# Instantiate and fit the model (on training set)
model = RandomForestRegressor()
# print(model.get_params()) # Checking the hyperparameters

model.fit(X_train, y_train)

# Check the score of the model (on the test set)
model.score(X_test, y_test)

0.806652667101436

Took 10 secs and better performace than the Ridge model

> 0.806652667101436

- Best Algorithm to train with

### **2.2 Picking a machine learning model for a classification problem**

[Let's go to the map...](..\assets\images\sklearn-ml-map.png)

In [90]:
# Get the data
import pandas as pd
import numpy as np

heart_disease = pd.read_csv('../Datasets/heart-disease.csv')
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [91]:
len(heart_disease)

303

Consulting the [map](..\assets\images\sklearn-ml-map.png) and it says try `LinearSVC`

In [92]:
# Import the LinearSVC estimator class
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split 

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

# Instantiate LinearSVC
clf = LinearSVC()
print(clf.get_params())

# Training on data
clf.fit(X_train, y_train)

# Evaluate the LinearSVC
clf.score(X_test, y_test)

{'C': 1.0, 'class_weight': None, 'dual': 'auto', 'fit_intercept': True, 'intercept_scaling': 1, 'loss': 'squared_hinge', 'max_iter': 1000, 'multi_class': 'ovr', 'penalty': 'l2', 'random_state': None, 'tol': 0.0001, 'verbose': 0}

0.8688524590163934

In [93]:
heart_disease['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

Trying different model

In [94]:
# Import the RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

# Instantiate RandomForestClassifier
clf = RandomForestClassifier()
print(clf.get_params())

# Training on data
clf.fit(X_train, y_train)

# Evaluate the RandomForestClassifier
clf.score(X_test, y_test)

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}

0.8524590163934426

#### **Tidbit:** (small interesting fact)

- If you have structured data:
    - Use ensemble methods because:

      1. the features are already organized
      2. tree ensembles are excellent at tabular patterns
      3. they often outperform deep learning on spreadsheets/tables
   
- If you have unstructured data:
    - Use deep learning or transfer learning because:

      1. the important features are hidden
      2. deep models can learn those features automatically
      3. pretrained models save time and data


For reference: [Visit basics(10)](../basic/basic_theory.ipynb)

In [95]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [96]:
what_were_covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm for our problem',
 '3. Fit the model/algorithm and use it to make pridictions on our data',
 '4. Eavaluating a model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all together!']

## **3. Fit the model/algorithm on our data and use it to make pridictions on our data**

### **3.1 Fitting to model with data**

- `X` = features, feature variables, data
- `y` = labels, target, target variables

In [97]:
# Import the RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

# Instantiate RandomForestClassifier
clf = RandomForestClassifier()

# Fit the model to the data (Training the machine learning model)
clf.fit(X_train, y_train)

# Evaluate the RandomForestClassifier (use the patterns the model has learned)
clf.score(X_test, y_test)

0.8524590163934426

In [98]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [99]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [100]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

#### **Random Forest model deep dive**

These resources will help you understand what's happening inside the Random Forest models we've been using.

- [Random Forest Wikipedia](https://en.wikipedia.org/wiki/Random_forest)
- [Random Forest Wikipedia (simple version)](https://simple.wikipedia.org/wiki/Random_forest)

### **3.2 Make preditions using machine learning model**

*2 ways to make predictions:*

1. `predict()`
2. `predict_proba()`

In [101]:
heart_disease.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [102]:
# Use a trained model to make predictions

# clf.predict(np.array[1, 7, 8, 3, 4]) # This doesn't work

In [103]:
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
179,57,1,0,150,276,0,0,112,1,0.6,1,1,1
228,59,1,3,170,288,0,0,159,0,0.2,1,0,3
111,57,1,2,150,126,1,1,173,0,0.2,2,1,3
246,56,0,0,134,409,0,0,150,1,1.9,1,2,3
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,69,1,2,140,254,0,0,146,0,2.0,1,3,3
104,50,1,2,129,196,0,1,163,0,0.0,2,0,2
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
193,60,1,0,145,282,0,0,142,1,2.8,1,2,3
184,50,1,0,150,243,0,0,128,0,2.6,1,0,3

In [104]:
clf.predict(X_test) # Predicted values

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [105]:
np.array(y_test) # Actual values

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [106]:
# Compare predictions to truth labels to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

# y_preds == y_test
# [True, False, True, False, ...]
# np.mean([True, False, True, False, ...])

np.float64(0.8524590163934426)

> model’s accuracy = total predictions / number of correct predictions
​

In [107]:
clf.score(X_test, y_test)

0.8524590163934426

In [108]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

In [109]:
clf.score(X, y) # Training and test data combined

0.9702970297029703

Make predictions with `predicit_proba()`

#### **Predict vs Predict_Proba: Final Decision vs Model Confidence**

When working with a **classification model**, these two methods answer **different questions**:

| Method | Main question it answers | What it returns | Example output | Best use |
|---|---|---|---|---|
| `predict()` | Which class should the model choose? | Final class label | `[1, 0, 1]` | When you want the direct prediction |
| `predict_proba()` | How confident is the model about each class? | Probability for every class | `[[0.20, 0.80], [0.91, 0.09], [0.35, 0.65]]` | When you want confidence and uncertainty |

---

#### 1. `predict()` -> the model's final answer

This method gives the **chosen class label** directly.

For a heart disease example:

- `0` = No heart disease
- `1` = Heart disease

```python
clf.predict(X_test[:3])
# array([1, 0, 1])
```

That means the model's final decisions are:

- first patient -> class `1`
- second patient -> class `0`
- third patient -> class `1`

Think of `predict()` as the model saying:

> "This is my final choice."

---

#### 2. `predict_proba()` -> the model's confidence for each class

This method gives the **probability of every possible class**.

```python
clf.predict_proba(X_test[:3])
# array([
#   [0.20, 0.80],
#   [0.91, 0.09],
#   [0.35, 0.65]
# ])
```

Read each row carefully:

- `[0.20, 0.80]` means 20% chance of class `0`, 80% chance of class `1`
- `[0.91, 0.09]` means 91% chance of class `0`, 9% chance of class `1`
- `[0.35, 0.65]` means 35% chance of class `0`, 65% chance of class `1`

Think of `predict_proba()` as the model saying:

> "Here is how confident I am about each possible answer."

---

#### 3. How they are connected

In many classification models, `predict()` chooses the class with the **highest probability** from `predict_proba()`.

Example:

- `[0.20, 0.80]` -> choose class `1`
- `[0.91, 0.09]` -> choose class `0`
- `[0.35, 0.65]` -> choose class `1`

So a simple memory trick is:

- `predict_proba()` = full confidence picture
- `predict()` = final selected answer

---

#### 4. Real-world analogy

Imagine a doctor reviewing a patient's test results:

- `predict()` = "The patient has heart disease."
- `predict_proba()` = "There is an 80% chance of heart disease and a 20% chance of no heart disease."

One gives the **decision**.
The other gives the **confidence behind the decision**.

---

#### 5. Most important takeaway

Use `predict()` when you only need the final class.
Use `predict_proba()` when you also want to understand **how certain** the model is.


> Short version: `predict()` tells you **what** the model chose. `predict_proba()` tells you **how sure** it was.

In [110]:
# predict_proba() returns probabilities of a classification label
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [111]:
# Let's predict on the same data
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

In [112]:
X_test[:5]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
179,57,1,0,150,276,0,0,112,1,0.6,1,1,1
228,59,1,3,170,288,0,0,159,0,0.2,1,0,3
111,57,1,2,150,126,1,1,173,0,0.2,2,1,3
246,56,0,0,134,409,0,0,150,1,1.9,1,2,3
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2

In [113]:
heart_disease['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64


predict() can also be used for regression models.

In [114]:
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [115]:
#  Import the RandomForestRegressor model class from the ensemble module
from sklearn.ensemble import RandomForestRegressor # Algorithm/Estimator
from sklearn.model_selection import train_test_split

# Setup random seed
np.random.seed(42)

# Create the data
X = housing_df.drop("target", axis=1)
y = housing_df['target']  # median house price in $100,000s
 
# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

# Instantiate the model instance
model = RandomForestRegressor()

# Fit the model to the data
model.fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)

In [116]:
y_preds[:10]

array([0.4939   , 0.75494  , 4.9285964, 2.54024  , 2.33176  , 1.6602201,
       2.3431   , 1.66311  , 2.47489  , 4.8344779])

In [117]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [118]:
# Compare the Predictions to the Truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds) # MAE

# It's a way to measure 
# how wrong your model's predictions are, on average.
# Lower MAE = better model (closer predictions)

0.32656738464147306

> **MAE tells you:** "On average, how many units was my model wrong by?"

In [119]:
housing_df['target']

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: target, Length: 20640, dtype: float64

In [120]:
model.score(X_test, y_test)

0.806652667101436

In [121]:
what_were_covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm for our problem',
 '3. Fit the model/algorithm and use it to make pridictions on our data',
 '4. Eavaluating a model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all together!']

## **4. Evaluating a machine learning model**

Three ways to evaluate Scikit-Learn models/estimators:

1. Estimator's built-in `score()` method
2. The `scoring` parameter
3. Problem-specific metric functions
   
You can read more about these [here](https://scikit-learn.org/stable/modules/model_evaluation.html)

### **4.1 Evaluating the model with `score()` method**

In [122]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Setup the random seed
np.random.seed(42)

# Create X and y
X = heart_disease.drop('target', axis = 1)
y = heart_disease['target']

# Create train/test
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

# Create classifier model instance
clf = RandomForestClassifier(n_estimators=1000)

# Fit classifier to training data
clf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1000)

In [123]:
# The highest values for .score() method is 1.0, lowest is 0.0
clf.score(X_train, y_train)

1.0

Accuracy = Total number of predictions / Number of correct predictions
​

In [124]:
clf.score(X_test, y_test)

# It gives the acurracy

0.8688524590163934

Let's use `.score()` on oure regression problem...

In [125]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Setup the random seed
np.random.seed(42)

# Make the data in X and y
X = housing_df.drop('target', axis=1)
y = housing_df['target']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

# Instaniate the Random Forest regressor
model = RandomForestRegressor()

# Fit the model on training data
model.fit(X_train, y_train)

RandomForestRegressor()

In [126]:
# The default score() evaluation metric is r^2 for regression algorithms
# Highest = 1.0, Lowest = 0.0
model.score(X_test, y_test)

0.806652667101436

### **4.2 Evaluating a model using the `scoring` parameter**

In [127]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Setup the random seed
np.random.seed(42)

# Create X and y
X = heart_disease.drop('target', axis = 1)
y = heart_disease['target']

# Create train/test
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

# Create classifier model instance
clf = RandomForestClassifier()

# Fit classifier to training data
clf.fit(X_train, y_train)

RandomForestClassifier()

In [128]:
clf.score(X_test, y_test)

0.8524590163934426

In [129]:
cross_val_score(clf, X, y, cv=5)

array([0.81967213, 0.86885246, 0.81967213, 0.78333333, 0.76666667])

<img src = '../assets/images/sklearn-cross-validation.png'>

*How the cross-validation working*

#### **Cross-Validation (CV)**

> **Goal:** get a *more trustworthy* estimate of how your model will do on **new/unseen data**.

> **Important:** CV does **not** magically make the model better — it makes the **evaluation** less dependent on luck.

---
### 1) Why do we need it? ("lucky" vs "unlucky")
If you do **one** train/test split, your score can change a lot depending on *which* rows ended up in the test set:
- **Lucky split**: test set happens to be easier → score looks **too high**
- **Unlucky split**: test set happens to be harder → score looks **too low**

> Analogy: tasting soup with one spoon. One scoop might be salty (unlucky) or bland (lucky). Multiple spoonfuls is fairer.

---
### 2) What is cross-validation?
**Cross-validation** = run several train/test experiments (in a structured way) and collect the scores.
Then you usually look at the **average** score (and how much the scores vary).

> Think: **multiple mini-tests** instead of one final test.

---
### 3) How does 5-fold CV work? (`cv=5`)
With `cv=5`, your dataset is split into **5 parts** (called *folds*):

> `[Fold 1] [Fold 2] [Fold 3] [Fold 4] [Fold 5]`

> You do 5 rounds: each fold becomes the test set once.

- Round 1: train on folds 2–5, test on fold 1
- Round 2: train on folds 1,3–5, test on fold 2
- Round 3: train on folds 1–2,4–5, test on fold 3
- Round 4: train on folds 1–3,5, test on fold 4
- Round 5: train on folds 1–4, test on fold 5

> Result: you get **5 scores** (one score per round).

> For classification, scikit-learn usually tries to keep class balance similar in each fold.

---
### 4) What does `cross_val_score` return?
```python
cross_val_score(clf, X, y)
```
This returns an array of scores, like:
`array([0.82, 0.79, 0.85, 0.80, 0.83])`

> The model was tested 5 times, so you got 5 scores.

Common summary:
```python
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()  # average performance
scores.std()   # stability (lower = more consistent)
```

> If the scores vary a lot, it means performance depends heavily on which data slice you tested on.

---
### 5) Why these two lines look the same
```python
cross_val_score(clf, X, y)
```
vs
```python
cross_val_score(clf, X, y, cv=5)
```
In scikit-learn, the default is usually **5 folds**, so these are often effectively the same.

> Writing `cv=5` is just **more explicit** and easier to remember later.

---
### 6) CV vs a single train/test split (quick comparison)
- **One split**: faster, but can be noisy (lucky/unlucky)
- **Cross-validation**: slower, but gives a more reliable estimate

> Memory sentence: **CV is multiple mini-tests, so your score is less about luck.**

In [130]:
cross_val_score(clf, X, y, cv=10)

array([0.90322581, 0.80645161, 0.87096774, 0.9       , 0.86666667,
       0.8       , 0.73333333, 0.86666667, 0.73333333, 0.8       ])

In [131]:
np.random.seed(42)

# Single training and test split score
clf_single_score = clf.score(X_test, y_test)

# Take mean of 5-fold cross-validation score
clf_cross_val_score = np.mean(cross_val_score(clf, X, y, cv=5))

# Comapre the two 
clf_single_score, clf_cross_val_score

# Cross-validation is usually more trustworthy because it evaluates the model on multiple splits and averages the scores.
# A single test split can be lucky or unlucky, so one score may overestimate or underestimate real-world performance.

(0.8524590163934426, np.float64(0.8248087431693989))

In [132]:
# Default scoring parameter of classifier = mean accuracy
# clf.score()

In [133]:
# Scoring parameter set to None by defualt
cross_val_score(clf, X, y, cv=5, scoring=None)

array([0.78688525, 0.86885246, 0.80327869, 0.78333333, 0.76666667])

#### **Default Scoring in `cross_val_score`**

When you run cross-validation **without** setting `scoring`, sklearn uses the model's **own default `.score()`** method.

So this:

```python
cross_val_score(model, X, y, cv=5)
```

means:
- "Use 5-fold CV"
- "For each fold, score using the model's default scoring rule"

**Common defaults:**
- **Classifier** (e.g., `RandomForestClassifier`) -> `.score()` = **Accuracy**
- **Regressor** (e.g., `RandomForestRegressor`) -> `.score()` = **R²**

So people say: **default CV scoring = estimator default scoring**.

If you want a different metric, set it explicitly, for example:

```python
cross_val_score(clf, X, y, cv=5, scoring="f1")
```

### **4.2.1 Classification model evaluation metrics**

1. Accuracy
2. Area under ROC curve
3. Confusion matrix
4. Classification report

#### **Accuracy**

In [141]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [136]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

clf = RandomForestClassifier()

cross_val_score = cross_val_score(clf, X, y, cv=5)

In [137]:
np.mean(cross_val_score)

np.float64(0.8248087431693989)

In [140]:
print(f"Heart Disease Classifier Cross-Validated Accuracy: {np.mean(cross_val_score) * 100:.2f} %")

Heart Disease Classifier Cross-Validated Accuracy: 82.48 %

#### **Area Under the Receiver Operating Characteristic Curve (`AUC/ROC`)**

- Area under curve (AUC)
- ROC

> ROC curves are a caparison of a model's true positive rate (TPR) Versus a model's false positive rate (FPR)

- `True postive` = model predicts 1 when truth is 1
- `False positive` = model predicts 1 when truth is 0
- `True negative` = model predicts 0 when truth is 0
- `False negative` = model predicts 0 when truth is 1

> - x-axis = FPR
> - y-axis = TPR

In [146]:
# Create X_test... etc
np.random.seed(42)

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

In [148]:
from sklearn.metrics import roc_curve  # noqa: F401

# Fit the Classifier
clf.fit(X_train, y_train)

# Make pridictions with probabilities
y_probs = clf.predict_proba(X_test)

y_probs[:10], len(y_probs)

(array([[0.87, 0.13],
        [0.4 , 0.6 ],
        [0.4 , 0.6 ],
        [0.92, 0.08],
        [0.21, 0.79],
        [0.16, 0.84],
        [0.42, 0.58],
        [0.95, 0.05],
        [0.98, 0.02],
        [0.48, 0.52]]),
 61)

In [151]:
clf.classes_

array([0, 1])

So in y_probs

> [probability of class 0, probability of class 1]

In [153]:
y_probs[:10]

array([[0.87, 0.13],
       [0.4 , 0.6 ],
       [0.4 , 0.6 ],
       [0.92, 0.08],
       [0.21, 0.79],
       [0.16, 0.84],
       [0.42, 0.58],
       [0.95, 0.05],
       [0.98, 0.02],
       [0.48, 0.52]])

In [150]:
y_probs_positive = y_probs[:, 1]
y_probs_positive[:10]

array([0.13, 0.6 , 0.6 , 0.08, 0.79, 0.84, 0.58, 0.05, 0.02, 0.52])

In [154]:
# Calculate FPR, TPR and Thresholds
fpr, tpr, thresholds = roc_curve(y_test, y_probs_positive)

In [155]:
# Check the False postive
fpr

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03448276, 0.03448276, 0.03448276, 0.06896552,
       0.06896552, 0.10344828, 0.10344828, 0.13793103, 0.13793103,
       0.17241379, 0.17241379, 0.24137931, 0.4137931 , 0.48275862,
       0.51724138, 0.72413793, 0.82758621, 0.93103448, 1.        ])

In [156]:
tpr

array([0.     , 0.09375, 0.1875 , 0.3125 , 0.375  , 0.40625, 0.5    ,
       0.53125, 0.59375, 0.625  , 0.65625, 0.6875 , 0.71875, 0.75   ,
       0.8125 , 0.84375, 0.9375 , 0.96875, 0.96875, 0.96875, 1.     ,
       1.     , 1.     , 1.     , 1.     ])

In [157]:
thresholds

array([ inf, 0.99, 0.94, 0.85, 0.84, 0.83, 0.79, 0.78, 0.76, 0.71, 0.69,
       0.68, 0.64, 0.6 , 0.58, 0.57, 0.35, 0.31, 0.14, 0.13, 0.12, 0.09,
       0.05, 0.04, 0.  ])