# 🤖 **Scikit-Learn**

## 📚 What is Scikit-Learn?

[**Scikit-Learn**](https://scikit-learn.org/stable/user_guide.html) (or sklearn) is a **Python library for Machine Learning**. It's a toolbox with pre-built algorithms to solve problems.

**Uses these libraries:**
- 🔢 NumPy - for numbers and arrays
- 🔬 SciPy - for scientific computing
- 📊 Matplotlib - for visualizations

---

### 🍳 Think of it Like Cooking:

- **NumPy** = Raw ingredients (flour, sugar, eggs)
- **Pandas** = Preparing ingredients (washing, cutting, measuring)
- **Scikit-Learn** = Recipe book (ready-made formulas to follow)
- **Matplotlib** = Plating (showing your final dish nicely)

<img src='..\assets\images\6-step-ml-framework.png'
style='background-color: white; padding: 20px;'>

## ✨ What Problems Does Scikit-Learn Solve?

**Real World Applications:**

| 🎯 Problem | 📌 What It Does | 💡 Example |
|:----------:|:-------------|:-------------|
| **Classification** | Predict categories/classes | Email spam detection (spam or not spam) |
| **Regression** | Predict numbers/values | House price prediction |
| **Clustering** | Group similar items together | Customer segmentation |
| **Data Preprocessing** | Clean and prepare data | Handle missing values, scale features |
| **Feature Selection** | Choose important features | Pick best predictors from many options |
| **Model Evaluation** | Measure how good your model is | Check accuracy, precision, recall |

---

[**Refresh the basics (ML)**](..\basic\basic_theory.ipynb)

## **Workflow**

<img src='..\assets\images\sklearn-workflow-title.png' style='background-color: white; padding: 20px;'>

# **Intoduction to Scikit-Learn (sklearn)**

What we are going to cover:

0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
2. Choose the right estimator/algorithm for our problem
3. Fit the model/algorithm and use it to make pridictions on our data
4. Eavaluating a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together!

In [1]:
# Let's listify the contents
what_were_covering = [
    "0. An end-to-end Scikit-Learn workflow",
    "1. Getting the data ready",
    "2. Choose the right estimator/algorithm for our problem",
    "3. Fit the model/algorithm and use it to make pridictions on our data",
    "4. Eavaluating a model",
    "5. Improve a model",
    "6. Save and load a trained model",
    "7. Putting it all together!"
]

In [2]:
what_were_covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm for our problem',
 '3. Fit the model/algorithm and use it to make pridictions on our data',
 '4. Eavaluating a model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all together!']

In [3]:
# Standard imports

import numpy as np  # noqa: F401
import pandas as pd  # noqa: F401
import matplotlib.pyplot as plt  # noqa: F401
%matplotlib inline

## **0. An end-to-end Scikit-Learn Workflow**

In [4]:
# 1. Get the data ready

import pandas as pd  # noqa: F811
heart_disease = pd.read_csv(r'..\Datasets\heart-disease.csv')
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
# Create X (Feature matrix)
X = heart_disease.drop('target', axis=1)

# Create Y (Label matrix/ Labels)
y = heart_disease['target']

# Expected output (classification)

**🔘 MICROWAVE ANALOGY:**
─────────────────────────────────────────
```list
Before you use it, you SET:
├─ Temperature? (high, medium, low)
├─ Time? (30 seconds, 2 minutes, 5 minutes?)
└─ Power level? (50%, 75%, 100%?)
```

**THESE ARE HYPERPARAMETERS! ← You decide them!**

```hirarchy
Then you:
└─ Press START → Microwave heats your food
                 (it LEARNS how to cook it best)
```

---

🤖 **Machine Learning:**
─────────────────────────────────────────
```text
YOU choose (Hyperparameters):
├─ How many trees? (10? 100? 500?)
├─ How deep trees? (shallow? deep?)
└─ Other settings...
```

Then the MODEL LEARNS (from your data)

In [6]:
## **2. Choose the right model and hyperparameters**

from sklearn.ensemble import RandomForestClassifier

# Creates a new ML model and naming it clf (classifier)
clf = RandomForestClassifier()

# We'll Keep the default hyperparameters
clf.get_params()

# clf.get_params()
# ↑ Shows ALL those default hyperparameters

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

HYPERPARAMETERS:
───────────────────────────────────────
- Settings you choose BEFORE training
- They control HOW the model learns
- You set them, the model uses them

---

`clf` is a MODEL ← An untrained RandomForest

- Has hyperparameters set to defaults
- Ready to be trained
- Waiting for data
- Can't predict yet (needs training first!)

In [7]:
# 3. Fit the model to the training data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Randomly splits your data into 2 groups:
# 80% to train the model,
# 20% to test if it actually learned (0.2)

```text
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
│        │        │        │                         │  │  └─ 20% for testing
│        │        │        │                         │  └─ targets
│        │        │        │                         └─ features
│        │        │        └─ Testing targets (answers for checking)
│        │        └─ Training targets (answers for learning)
│        └─ Testing features (unseen data to test on)
└─ Training features (data to learn from)
```

In [8]:
clf.fit(X_train, y_train)

# Trains the model by showing it the features (X_train)
# and their correct answers (y_train),
# so it learns the patterns

RandomForestClassifier()

In [9]:
X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
174,60,1,0,130,206,0,0,132,1,2.4,1,2,3
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2
26,59,1,2,150,212,1,1,157,0,1.6,2,0,2
146,44,0,2,118,242,0,1,149,0,0.3,1,1,2
170,56,1,2,130,256,1,0,142,1,0.6,1,1,1

In [10]:
X_test.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
51,66,1,0,120,302,0,0,151,0,0.4,1,0,2
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1
57,45,1,0,115,260,0,0,185,0,0.0,2,0,2
66,51,1,2,100,222,0,1,143,1,1.2,1,0,2
279,61,1,0,138,166,0,0,125,1,3.6,1,1,2

In [11]:
# Makes predictions on NEW, UNSEEN data

y_preds = clf.predict(X_test)
y_preds

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1])

In [12]:
y_test

51     1
5      1
57     1
66     1
279    0
      ..
182    0
271    0
248    0
84     1
2      1
Name: target, Length: 61, dtype: int64

In [13]:
# 4. Evaluate the model on the training data and test data

# Training Accuracy
clf.score(X_train, y_train)

1.0

**Means:** Model got 100% correct on the data it learned from!

In [14]:
clf.score(X_test, y_test)

0.8032786885245902

**Means:** Model got 86.88% correct on NEW data it never saw!

```python
clf.score(X_test, y_test)
│   │     │       │
│   │     │       └─ Actual answers (truth)
│   │     └─ Features to predict on
│   └─ "Calculate accuracy" command
└─ Your model
```

**Process:**
1. Model predicts on X_test
2. Compares predictions to y_test (truth)
3. Counts how many it got right
4. Returns: (correct / total) as decimal

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))
# What it does: 
# Gives you a FULL report with multiple metrics

              precision    recall  f1-score   support

           0       0.88      0.71      0.79        31
           1       0.75      0.90      0.82        30

    accuracy                           0.80        61
   macro avg       0.81      0.80      0.80        61
weighted avg       0.82      0.80      0.80        61

In [16]:
confusion_matrix(y_test, y_preds)
# What it does:
# Shows WHERE your model is making mistakes

array([[22,  9],
       [ 3, 27]])

CONFUSION MATRIX:
═══════════════════════════════════════════════════════
```text
                   PREDICTED
                 No Disease  Disease
               ┌──────────┬──────────┐
        No (0) │    25    │    3     │  ← Actually No Disease
ACTUAL         ├──────────┼──────────┤
   Disease (1) │    5     │    28    │  ← Actually Disease
               └──────────┴──────────┘
```

**Reading it:**
- Top-left (25): Correctly predicted "No Disease" ✓
- Top-right (3): Said "Disease" but was actually "No Disease" ✗
- Bottom-left (5): Said "No Disease" but was actually "Disease" ✗
- Bottom-right (28): Correctly predicted "Disease" ✓

In [17]:
accuracy_score(y_test, y_preds)
# What it does:
# Calculates accuracy (same as .score() but more flexible)

0.8032786885245902

In [18]:
# 5. Improve a model
# Try different amount of n_estimators (hyperparameter)

# np.random.seed(42)
# for i in range(10, 100, 10):
#     print(f"Trying model with {i} estimators...")
#     clf = RandomForestClassifier(n_estimators=i)
#     clf.fit(X_train, y_train)
#     print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100:2f} %")
#     print()

In [19]:
# 6. Save the model and load it 
import pickle

pickle.dump(clf, open("random_forest_model.pkl", "wb"))

# .pkl = Python Pickle file
# It SAVES your trained model to a file
# so you can reload it later without retraining

```text
pickle.dump(clf, open("random_forest_model.pkl", "wb"))

│      │    │    │
│      │    │    └─ Create file, write binary
│      │    └─ Your trained model
│      └─ Save to file command
└─ Import pickle library

RESULT: Model saved! Can use forever! 💾
```

In [20]:
# Loads your saved trained model from the file back into memory.
loaded_model = pickle.load(open('random_forest_model.pkl', 'rb'))

# Tests the loaded model to verify it works and shows its accuracy
loaded_model.score(X_test, y_test)

0.8032786885245902

In [21]:
what_were_covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm for our problem',
 '3. Fit the model/algorithm and use it to make pridictions on our data',
 '4. Eavaluating a model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all together!']

### **Summary**

In [22]:
# Importing the modules
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt  # noqa: F401, F811
import numpy as np  # noqa: F401, F811
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 
import pickle

# 0. Loading the data
heart_disease = pd.read_csv(r'..\Datasets\heart-disease.csv')

# 1. Getting the data ready
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# 2. Choose the model and hyperparameters
# from sklearn.ensemble import RandomTreesEmbedding
clf = RandomForestClassifier()
clf.get_params()
# 3. Splitting the data into training data and testing data
# from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 4. Fit the model with training data
clf.fit(X_train, y_train)

# 5. Evaluate the model on the training data and test data
## Testing on training data
y_preds = clf.predict(X_test)
clf.score(X_train, y_train)

## Testing on testing data
clf.score(X_test, y_test)

## Classification report 
print("Classification report: \n")
print(classification_report(y_test, y_preds))
print()

## Confusion matrix
print("Confusion matrix: \n")
print(confusion_matrix(y_test, y_preds))
print()

## Accuracy score
print("Accuracy score: ")
print(accuracy_score(y_true=y_test, y_pred=y_preds), "\n")

# 6. Improve a model
print("Improving model: ")
clf = RandomForestClassifier(n_estimators=90)  # trying out different params values
clf.fit(X_train, y_train)
y_preds = clf.predict(X_test)

clf.score(X_test, y_test)
print("Classification report: \n")
print(classification_report(y_test, y_preds))
print()
print("Confusion matrix: \n")
print(confusion_matrix(y_test, y_preds))
print()
print("Accuracy Score \n")
print(accuracy_score(y_true=y_test, y_pred=y_preds))
print()

# 6. Save the model and reload it for future use
print("Saving the model...")
pickle.dump(clf, open("random_forest_model.pkl", "wb"))

print("Loading the model...")
pickle.load(open("random_forest_model.pkl", "rb"))
print("Voila!!! Done...")

Classification report:

              precision    recall  f1-score   support

           0       0.84      0.84      0.84        31
           1       0.83      0.83      0.83        30

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61


Confusion matrix:

[[26  5]
 [ 5 25]]

Accuracy score:
0.8360655737704918

Improving model:
Classification report:

              precision    recall  f1-score   support

           0       0.86      0.77      0.81        31
           1       0.79      0.87      0.83        30

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61


Confusion matrix:

[[24  7]
 [ 4 26]]

Accuracy Score

0.819672131147541

Saving the model...
Loading the model...
Voila!!! Done...

#### **Warning Section**

In [23]:
# import warnings
# warnings.filterwarnings("ignore")  # use "default" -> Will show warnings then 

# Hides all warning messages
# Makes output cleaner
# Code still runs normally
# Use when you know what you are doing

In [24]:
import sklearn  # noqa: F811
sklearn.show_versions()

System:
    python: 3.14.2 | packaged by Anaconda, Inc. | (main, Dec 19 2025, 11:44:48) [MSC v.1929 64 bit (AMD64)]
executable: d:\Eakem\Learning ML and DS\Learning ML\env\python.exe
   machine: Windows-11-10.0.26200-SP0

Python dependencies:
      sklearn: 1.8.0
          pip: 26.0.1
   setuptools: 80.10.2
        numpy: 2.4.2
        scipy: 1.17.0
       Cython: None
       pandas: 3.0.0
   matplotlib: 3.10.8
       joblib: 1.5.3
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: mkl
    num_threads: 8
         prefix: mkl_rt
       filepath: D:\Eakem\Learning ML and DS\Learning ML\env\Library\bin\mkl_rt.2.dll
        version: 2025.0-Product
threading_layer: intel

       user_api: openmp
   internal_api: openmp
    num_threads: 16
         prefix: libiomp
       filepath: D:\Eakem\Learning ML and DS\Learning ML\env\Library\bin\libiomp5md.dll
        version: None

       user_api: openmp
   internal_api: openmp
    num_threads: 16
         prefix: vcomp
       filepath: D:\Eakem\Learning ML and DS\Learning ML\env\vcomp140.dll
        version: None

#### **Conda Workflow (Miniconda, Beginner Friendly)**

Use this quick guide when maintaining your Python environment.

**What each update command does**
- `conda update conda` updates the Conda tool itself (best done in `base`).
- `conda update package_name` updates one package in your active environment.
- `conda update --all` updates all packages in your active environment.

**1. Start (update Conda tool)**

```bash
conda env list
conda activate base
conda update conda
```

**2. Move to your project environment**

```bash
conda activate your_env_name
```

**3. Search and check a package**

```bash
conda search package_name
conda search package_name --info
conda list package_name
```

**4. Update one specific package**

```bash
conda update package_name
# Example
conda update scikit-learn
```

**5. Update all packages in this environment**

```bash
conda update --all
```

**6. Uninstall a package**

```bash
conda remove package_name
# Example
conda remove scikit-learn
```

**7. Verify installed versions**

```bash
conda list
```

**Safe tip before big updates**

```bash
conda create -n your_env_name_backup --clone your_env_name
```

**Miniconda note**
- If you use Miniconda, you usually do not need `conda update anaconda`.

# **Workflow in detail**

## **1. Getting our data ready to be used with machine learning**

**Three main things we need to do:**

1. Split the data into features and labels (Usually `X` & `y`)
2. Filling (aslo called imputing) or disregarding missing values
3. Converting non-numerical values to numerical values (also called feature encoding)

In [25]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [27]:
X = heart_disease.drop('target', axis=1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [28]:
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [ ]:
# Split the data into training and test sets 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

In [30]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [31]:
X.shape

(303, 13)

In [33]:
X.shape[0] * 0.8

242.4

In [34]:
242 + 61

303

In [32]:
len(heart_disease)

303