# **NumPy**

In [235]:
import numpy as np
import pandas as pd

In [236]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

a3 = np.array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [237]:
a1

array([1, 2, 3])

In [238]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [239]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### ***Reshaping and Transposing***

#### **What is Reshape?**
Reshape changes the shape of an array. The data stays the same, but the layout changes. For example, change 6 numbers in a line to 2 rows and 3 columns.

**Why use Reshape?**
- Make arrays same size to do math together
- Get data in right format for models
- Rearrange without losing data

#### **What is Transpose?**
Transpose flips an array. Rows become columns, columns become rows. Use `.T` to do it.

**Why use Transpose?**
- Flip data from rows to columns
- Get data ready for calculations
- Fix array shape when needed

In [240]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [241]:
a2.shape

(2, 3)

In [242]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [243]:
a3.shape

(2, 3, 3)

In [244]:
# a2 * a3
# ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3)

In [245]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [246]:
# Reshaping

a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [247]:
a2.reshape(2, 3, 1).shape

(2, 3, 1)

In [248]:
a3.shape

(2, 3, 3)

In [249]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [250]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [251]:
# np.newline -> learn difference

In [252]:
a2 , a2.shape

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 (2, 3))

In [253]:
# Transpose

a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [254]:
a2.T.shape

(3, 2)

In [255]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [256]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

### **Dot product**

- [Learn More](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

---

**How to multiply matrix**

>- |   - - -
>- |
>- |


**Use:**
- a@b
- np.dot(a, b)

In [257]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))

mat2 = np.random.randint(10, size=(5, 3))

In [258]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [259]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [260]:
mat1.shape , mat2.shape

((5, 3), (5, 3))

In [261]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [262]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [263]:
# Element-wise multiplication (Hadamard product)
# not dot product 
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [264]:
# # This will fail as the inner dimensions of the matrices do not match
# np.dot(mat1, mat1)

---

## **Element-Wise Multiplication vs Dot Product**

### **Example: Two Small Matrices**

```
mat1 = [1  2]      mat2 = [3  4]
       [5  6]             [7  8]
```

---

### **1️⃣ ELEMENT-WISE MULTIPLICATION (Hadamard Product)**
**Use:** `mat1 * mat2`

Multiply matching positions, one by one:

```
[1  2]   *   [3  4]   =   [1×3  2×4]   =   [3   8]
[5  6]       [7  8]       [5×7  6×8]       [35  48]
```

**Result shape:** Same as input `(2, 2)`

---

### **2️⃣ DOT PRODUCT (Matrix Multiplication)**
**Use:** `mat1 @ mat2` or `np.dot(mat1, mat2)`

**RULE:** `(rows1, cols1) @ (rows2, cols2)` → `(rows1, cols2)`

**Constraint:** `cols1 must equal rows2`

For dot product: Multiply rows of mat1 by columns of mat2, then sum:

```
mat1 shape = (2, 2)
mat2 shape = (2, 2)  ✅ Can multiply! (2 == 2)

Result = [1×3 + 2×7,    1×4 + 2×8]   =   [17  20]
         [5×3 + 6×7,    5×4 + 6×8]       [57  68]
```

**Result shape:** `(2, 2)` (rows of mat1, cols of mat2)

---

### **Key Difference**

| Operation | Symbol | Formula | Result |
|-----------|--------|---------|--------|
| **Element-Wise** | `*` | Position by position | Same shape |
| **Dot Product** | `@` | Rows × Columns (sum) | (rows1, cols2) |

**Element-wise:** `[3, 8, 35, 48]` (just multiply)  
**Dot product:** `[17, 20, 57, 68]` (multiply + sum)

In [265]:
# Since dim1 of mat1 == dim0 of ma2

mat_trans = np.transpose(mat2)

In [266]:
# Dot prdoct

np.dot(mat1, mat_trans)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [267]:
mat1@mat_trans

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [268]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [269]:
mat3.shape

(5, 5)

---

### **Why and When Use Dot Product?**

**WHY:**
- Get **one final number** from many numbers (like calculating a score)
- Core operation in **all ML models** — every prediction uses dot product
- Combine features with weights: `prediction = data @ weights`

**WHEN:**
- Making predictions (house price, test score, any ML model output)
- Measuring similarity between two vectors
- Neural networks (every layer uses dot product)

**Example:**  
House features: `[1500 sqft, 3 bedrooms, 10 years old]`  
Model weights: `[200, 5000, -1000]`  
Price = `1500×200 + 3×5000 + 10×(-1000)` = **$305,000** ← That's dot product!

## **Exercise - Nut butter store sales**

In [270]:
# Number of jars sold

np.random.seed(0)
sales_amount = np.random.randint(20, size=(5, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [271]:
# Create weekly_sales DataFrame

weekly_sales = pd.DataFrame(sales_amount,
                            index = ['Mon', 'Tue', 'Wed', 'Thurs', 'Fri'],
                            columns= ['Almond butter', 'Peanut butter', 'Cashew butter'])
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [272]:
# Create prices array of each specific type of jar

prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [273]:
prices.shape

(3,)

In [274]:
# Create butter_prices DataFrame

butter_prices = pd.DataFrame(prices.reshape(1,3), 
                             index = ['Price'], 
                             columns= ['Almond butter', 'Peanut butter', 'Cashew butter'])

butter_prices

       Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [275]:
sales_amount, sales_amount.shape

(array([[12, 15,  0],
        [ 3,  3,  7],
        [ 9, 19, 18],
        [ 4,  6, 12],
        [ 1,  6,  7]], dtype=int32),
 (5, 3))

In [276]:
sales_amount.T, sales_amount.T.shape

(array([[12,  3,  9,  4,  1],
        [15,  3, 19,  6,  6],
        [ 0,  7, 18, 12,  7]], dtype=int32),
 (3, 5))

In [277]:
prices, prices.shape

(array([10,  8, 12]), (3,))

In [278]:
# Total_sales = prices @ sales_amount
# Total_sales

In [279]:
Total_sales = prices @ sales_amount.T
Total_sales

array([240, 138, 458, 232, 142])

In [280]:
Total_sales.shape

(5,)

---

## **IMPORTANT: 1D Arrays Don't Change Shape in Dot Product**

**Common Confusion:**
- Does `(3,)` convert to `(1, 3)` when doing dot product? **NO!**

**What Actually Happens:**

```
1D Array stays 1D:
prices.shape = (3,)
result = prices @ sales_amount.T
result.shape = (5,)  ← Still 1D! No conversion!

2D Array stays 2D:
prices_2d.shape = (1, 3)
result_2d = prices_2d @ sales_amount.T
result_2d.shape = (1, 5)  ← Still 2D!
```

**The Rule:**
- NumPy **does NOT convert shapes**
- It just **handles the math correctly**
- 1D stays 1D, 2D stays 2D

**In our example:**
```
prices = [10, 8, 12]          shape (3,)
prices @ sales_amount.T       
= [revenue_mon, revenue_tue, revenue_wed, revenue_thu, revenue_fri]
shape (5,) ← 1D output!
```

NumPy is smart about dimensions. No hidden conversions! ✅

---

## **ROWS vs COLUMNS Confusion**

**Visual Example:**
```
Matrix = [[1,  2,  3],
          [4,  5,  6]]

ROWS (horizontal):
  Row 1 = [1, 2, 3]
  Row 2 = [4, 5, 6]

COLUMNS (vertical):
  Col 1 = [1, 4]
  Col 2 = [2, 5]
  Col 3 = [3, 6]

Shape (2, 3) means:
  2 rows
  3 columns
```

---

### **How Rows & Columns Matter in Dot Product**

**Rule:** `(rows1, cols1) @ (rows2, cols2)` ← **cols1 MUST equal rows2**

**Example:**
```
Matrix A: shape (2, 3)  ← 2 rows, 3 columns
Matrix B: shape (3, 5)  ← 3 rows, 5 columns

A @ B works because 3 (cols of A) == 3 (rows of B) ✅

Result: (2, 5)  ← Keep rows from A, keep cols from B
```

---

### **In Our Butter Exercise**

```
prices.shape = (3,)                    ← 3 prices
sales_amount = (5, 3)                  ← 5 days, 3 types per day

We transpose: sales_amount.T = (3, 5)  ← Now 3 rows, 5 columns

prices @ sales_amount.T
(3,) @ (3, 5)
       ↓
   Match! ✅
   
Result: (5,)  ← 5 daily revenues
```

**Why transpose?** We rearranged the data so:
- 3 rows matched 3 prices
- 5 columns gave us 5 days

In [281]:
butter_prices

       Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [282]:
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [283]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [284]:
weekly_sales.T

               Mon  Tue  Wed  Thurs  Fri
Almond butter   12    3    9      4    1
Peanut butter   15    3   19      6    6
Cashew butter    0    7   18     12    7

In [285]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

       Mon  Tue  Wed  Thurs  Fri
Price  240  138  458    232  142

In [286]:
daily_sales.T

       Price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [287]:
daily_sales.shape

(1, 5)

In [288]:
weekly_sales.shape

(5, 3)

In [289]:
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [290]:
# # Doesn't work, not the right shape
# weekly_sales["Total ($)"] = daily_sales

In [291]:
weekly_sales["Total ($)"] = daily_sales.T

In [292]:
weekly_sales

       Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tue                3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

### **Comparison Operators**

In [293]:
a1

array([1, 2, 3])

In [294]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [295]:
# Element like comparison   
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [296]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [297]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [298]:
type(bool_array),  bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [299]:
a1 > 5

array([False, False, False])

In [300]:
a1 < 5

array([ True,  True,  True])

In [301]:
a1

array([1, 2, 3])

In [302]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [303]:
a1 == a1

array([ True,  True,  True])

In [304]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [305]:
a1 != a2

array([[False, False,  True],
       [ True,  True,  True]])

## ***Sorting array***

In [306]:
np.random.seed(0)

random_array = np.random.randint(10, size=(3, 5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]], dtype=int32)

In [307]:
# sorts the elements in your array from smallest to largest.
np.sort(random_array)

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]], dtype=int32)

### **Axis**

- Axis tells NumPy which direction to perform an operation (like sum, mean, max, etc.)
- **Think of it as:** "Which way should I collapse/combine the data?"


> axis=0  →  Go DOWN (↓) the rows (vertical, column-wise)

> axis=1  →  Go ACROSS (→) the columns (horizontal, row-wise)

```text
     axis=1 →
   ┌─────────────┐
a  │ 1   2   3   │
x  │ 4   5   6   │
i  │ 7   8   9   │
s  └─────────────┘
=
0
↓
```
---


> **Example:**

```python

matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])
#         Shape: (2, 3)  → 2 rows, 3 columns

# axis=0: Collapse ROWS (eliminate row dimension)
result = np.sum(matrix, axis=0)
print(result)  # [50, 70, 90]
print(result.shape)  # (3,)  ← Only columns left!

#     10  20  30
#   + 40  50  60
#   -----------
#     50  70  90


# axis=1: Collapse COLUMNS (eliminate column dimension)
result = np.sum(matrix, axis=1)
print(result)  # [60, 150]
print(result.shape)  # (2,)  ← Only rows left!

#   10 + 20 + 30 = 60
#   40 + 50 + 60 = 150
```

---
>axis=0 → Compare going DOWN ↓
         Result has COLUMN count (width stays)
         Tells you which ROW wins

>axis=1 → Compare going ACROSS →
         Result has ROW count (height stays)
         Tells you which COLUMN wins

In [308]:
# returns the INDICES (positions) that would sort the array, NOT the sorted values themselves!
# Think of it as: "Tell me the ORDER of positions to pick elements to make it sorted"

np.argsort(random_array)

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3]])

In [309]:
# returns the INDEX (position) of the SMALLEST value in the array.
# covert it all in 1-d array

np.argmin(random_array)

np.int64(1)

In [310]:
# returns the INDEX (position) of the LARGEST value in the array.
np.argmax(random_array)

np.int64(5)

In [311]:
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]], dtype=int32)

In [312]:
# Finding MINIMUM in Each Row (argmin)

np.argmin(random_array, axis=1)

array([1, 3, 4])

**How it works:**
```python

Row 0: [5, 0, 3, 3, 7]  →  Smallest is 0 at index 1  → Result: 1
        ↓  ↓  ↓  ↓  ↓
       [0][1][2][3][4]
           ↑ MIN!

Row 1: [9, 3, 5, 2, 4]  →  Smallest is 2 at index 3  → Result: 3
        ↓  ↓  ↓  ↓  ↓
       [0][1][2][3][4]
                 ↑ MIN!

Row 2: [7, 6, 8, 8, 1]  →  Smallest is 1 at index 4  → Result: 4
        ↓  ↓  ↓  ↓  ↓
       [0][1][2][3][4]
                    ↑ MIN!

RESULT: [1, 3, 4]
```

In [313]:
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]], dtype=int32)

In [314]:
# Finding MINIMUM in Each Column (argmin)

np.argmin(random_array, axis=0)

array([0, 0, 0, 1, 2])

**How it works:**

```python

        Col 0   Col 1   Col 2   Col 3   Col 4
        ↓       ↓       ↓       ↓       ↓
Row 0:  5       0       3       3       7
Row 1:  9       3       5       2       4
Row 2:  7       6       8       8       1
        ↓       ↓       ↓       ↓       ↓
MIN:    5       0       3       2       1
        @row0   @row0   @row0   @row1   @row2

RESULT: [0, 0, 0, 1, 2]
```

In [315]:
a1

array([1, 2, 3])

In [316]:
np.sort(a1)

array([1, 2, 3])

In [317]:
np.argsort(a1)

array([0, 1, 2])

In [318]:
np.argmin(a1)

np.int64(0)

In [319]:
np.argmax(a1)

np.int64(2)

## **Practical example - NumPy in Action!!**

In [320]:
# Turn image into a numpy array

from matplotlib.image import imread

**panda**

<img src = "..\assets\images\panda.png">

In [321]:
panda = imread(r"..\assets\images\panda.png")
print(panda)
print(type(panda))

[[[0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  ...
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]]

 [[0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  ...
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]]

 [[0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  ...
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]]

 ...

 [[0.13333334 0.07450981 0.05490196]
  [0.12156863 0.0627451  0.04313726]
  [0.10980392 0.05098039 0.03137255]
  ...
  [0.02745098 0.02745098 0.03529412]
  [0.02745098 0.02745098 0.03529412]
  [0.02745098 0.02745098 0.03529412]]

 [[0.13333334 0.07450981 0.05490196]
  [0.12156863 0.0627451  0.04313726]
  [0.12156863 0.0627451  0.04313726]
  ...
  [0.02352941 0.02352941 0.03137255]
  [0.02352941 0.02352941 0.03137255]
  [0.02352941 0.02352941 0.03137255]]

 [[0.13333334 0.07450981 0.05490196]
  [0.12156863 0.0627451  0.04313726]
  [0.12156863 0.0627451  0.04313726]
  ...
  [0.02352941 0.02352941 0.03137255]
  [0.02352941 0.02352941 0.03137255]
  [0.02352941 0.02352941 0.03137255]]]
<class 'numpy.ndarray'>

In [322]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [323]:
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]],
      shape=(2, 3500, 3), dtype=float32)

**car**

<img src = "..\assets\images\Porsche 911.png">

In [324]:
car = imread(r"..\assets\images\Porsche 911.png")
car

array([[[0.8235294 , 0.7058824 , 0.5568628 ],
        [0.8627451 , 0.7490196 , 0.6156863 ],
        [0.81960785, 0.7176471 , 0.5882353 ],
        ...,
        [0.48235294, 0.3372549 , 0.23529412],
        [0.63529414, 0.4117647 , 0.29411766],
        [0.5764706 , 0.35686275, 0.21176471]],

       [[0.83137256, 0.7058824 , 0.5529412 ],
        [0.8666667 , 0.73333335, 0.62352943],
        [0.8392157 , 0.7176471 , 0.6039216 ],
        ...,
        [0.34117648, 0.22745098, 0.20392157],
        [0.56078434, 0.34901962, 0.23921569],
        [0.60784316, 0.38039216, 0.23529412]],

       [[0.7882353 , 0.6666667 , 0.4862745 ],
        [0.8       , 0.67058825, 0.50980395],
        [0.8352941 , 0.70980394, 0.56078434],
        ...,
        [0.16078432, 0.10980392, 0.13725491],
        [0.44705883, 0.2784314 , 0.21176471],
        [0.54509807, 0.32941177, 0.21176471]],

       ...,

       [[0.44705883, 0.40784314, 0.36862746],
        [0.49411765, 0.43529412, 0.42352942],
        [0.49411765, 0.43529412, 0.40784314],
        ...,
        [0.50980395, 0.43137255, 0.3882353 ],
        [0.50980395, 0.4392157 , 0.38431373],
        [0.5058824 , 0.45490196, 0.38039216]],

       [[0.47058824, 0.42352942, 0.36862746],
        [0.46666667, 0.41568628, 0.38039216],
        [0.47058824, 0.43529412, 0.40784314],
        ...,
        [0.5294118 , 0.45882353, 0.4117647 ],
        [0.5254902 , 0.4627451 , 0.40392157],
        [0.5019608 , 0.47058824, 0.3882353 ]],

       [[0.5058824 , 0.43137255, 0.40784314],
        [0.4862745 , 0.42352942, 0.37254903],
        [0.5372549 , 0.45882353, 0.42352942],
        ...,
        [0.53333336, 0.47843137, 0.43529412],
        [0.52156866, 0.46666667, 0.42352942],
        [0.5058824 , 0.45882353, 0.4117647 ]]],
      shape=(1080, 1920, 3), dtype=float32)

In [325]:
car.size , car.shape, car.ndim

(6220800, (1080, 1920, 3), 3)

In [326]:
car[:1]

array([[[0.8235294 , 0.7058824 , 0.5568628 ],
        [0.8627451 , 0.7490196 , 0.6156863 ],
        [0.81960785, 0.7176471 , 0.5882353 ],
        ...,
        [0.48235294, 0.3372549 , 0.23529412],
        [0.63529414, 0.4117647 , 0.29411766],
        [0.5764706 , 0.35686275, 0.21176471]]],
      shape=(1, 1920, 3), dtype=float32)

**Dog**

<img src = "..\assets\images\dog-photo.png">

In [327]:
dog = imread(r"..\assets\images\dog-photo.png")

In [328]:
dog.size, dog.shape, dog.ndim

(993600, (432, 575, 4), 3)

In [329]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]],
      shape=(1, 575, 4), dtype=float32)