# **NumPy**

In [2]:
import numpy as np
import pandas as pd

In [3]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

a3 = np.array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [4]:
a1

array([1, 2, 3])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### ***Reshaping and Transposing***

#### **What is Reshape?**
Reshape changes the shape of an array. The data stays the same, but the layout changes. For example, change 6 numbers in a line to 2 rows and 3 columns.

**Why use Reshape?**
- Make arrays same size to do math together
- Get data in right format for models
- Rearrange without losing data

#### **What is Transpose?**
Transpose flips an array. Rows become columns, columns become rows. Use `.T` to do it.

**Why use Transpose?**
- Flip data from rows to columns
- Get data ready for calculations
- Fix array shape when needed

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a2.shape

(2, 3)

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# a2 * a3
# ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3)

In [12]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [13]:
# Reshaping

a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [14]:
a2.reshape(2, 3, 1).shape

(2, 3, 1)

In [15]:
a3.shape

(2, 3, 3)

In [16]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [17]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [18]:
# np.newline -> learn difference

In [19]:
a2 , a2.shape

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 (2, 3))

In [20]:
# Transpose

a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [21]:
a2.T.shape

(3, 2)

In [22]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

### **Dot product**

- [Learn More](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

---

**How to multiply matrix**

>- |   - - -
>- |
>- |


**Use:**
- a@b
- np.dot(a, b)

In [24]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))

mat2 = np.random.randint(10, size=(5, 3))

In [25]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [26]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [27]:
mat1.shape , mat2.shape

((5, 3), (5, 3))

In [28]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [29]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [30]:
# Element-wise multiplication (Hadamard product)
# not dot product 
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [31]:
# This will fail as the inner dimensions of the matrices do not match
np.dot(mat1, mat1)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

---

## **Element-Wise Multiplication vs Dot Product**

### **Example: Two Small Matrices**

```
mat1 = [1  2]      mat2 = [3  4]
       [5  6]             [7  8]
```

---

### **1️⃣ ELEMENT-WISE MULTIPLICATION (Hadamard Product)**
**Use:** `mat1 * mat2`

Multiply matching positions, one by one:

```
[1  2]   *   [3  4]   =   [1×3  2×4]   =   [3   8]
[5  6]       [7  8]       [5×7  6×8]       [35  48]
```

**Result shape:** Same as input `(2, 2)`

---

### **2️⃣ DOT PRODUCT (Matrix Multiplication)**
**Use:** `mat1 @ mat2` or `np.dot(mat1, mat2)`

**RULE:** `(rows1, cols1) @ (rows2, cols2)` → `(rows1, cols2)`

**Constraint:** `cols1 must equal rows2`

For dot product: Multiply rows of mat1 by columns of mat2, then sum:

```
mat1 shape = (2, 2)
mat2 shape = (2, 2)  ✅ Can multiply! (2 == 2)

Result = [1×3 + 2×7,    1×4 + 2×8]   =   [17  20]
         [5×3 + 6×7,    5×4 + 6×8]       [57  68]
```

**Result shape:** `(2, 2)` (rows of mat1, cols of mat2)

---

### **Key Difference**

| Operation | Symbol | Formula | Result |
|-----------|--------|---------|--------|
| **Element-Wise** | `*` | Position by position | Same shape |
| **Dot Product** | `@` | Rows × Columns (sum) | (rows1, cols2) |

**Element-wise:** `[3, 8, 35, 48]` (just multiply)  
**Dot product:** `[17, 20, 57, 68]` (multiply + sum)

In [ ]:
# Since dim1 of mat1 == dim0 of ma2

mat_trans = np.transpose(mat2)

In [ ]:
# Dot prdoct

np.dot(mat1, mat_trans)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [ ]:
mat1@mat_trans

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [ ]:
mat3.shape

(5, 5)

---

### **Why and When Use Dot Product?**

**WHY:**
- Get **one final number** from many numbers (like calculating a score)
- Core operation in **all ML models** — every prediction uses dot product
- Combine features with weights: `prediction = data @ weights`

**WHEN:**
- Making predictions (house price, test score, any ML model output)
- Measuring similarity between two vectors
- Neural networks (every layer uses dot product)

**Example:**  
House features: `[1500 sqft, 3 bedrooms, 10 years old]`  
Model weights: `[200, 5000, -1000]`  
Price = `1500×200 + 3×5000 + 10×(-1000)` = **$305,000** ← That's dot product!

## **Exercise - Nut butter store sales**

In [ ]:
# Number of jars sold

np.random.seed(0)
sales_amount = np.random.randint(20, size=(5, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [ ]:
# Create weekly_sales DataFrame

weekly_sales = pd.DataFrame(sales_amount,
                            index = ['Mon', 'Tue', 'Wed', 'Thurs', 'Fri'],
                            columns= ['Almond butter', 'Peanut butter', 'Cashew butter'])
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
# Create prices array of each specific type of jar

prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [ ]:
prices.shape

(3,)

In [ ]:
# Create butter_prices DataFrame

butter_prices = pd.DataFrame(prices.reshape(1,3), 
                             index = ['Price'], 
                             columns= ['Almond butter', 'Peanut butter', 'Cashew butter'])

butter_prices

       Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [ ]:
sales_amount, sales_amount.shape

(array([[12, 15,  0],
        [ 3,  3,  7],
        [ 9, 19, 18],
        [ 4,  6, 12],
        [ 1,  6,  7]], dtype=int32),
 (5, 3))

In [ ]:
sales_amount.T, sales_amount.T.shape

(array([[12,  3,  9,  4,  1],
        [15,  3, 19,  6,  6],
        [ 0,  7, 18, 12,  7]], dtype=int32),
 (3, 5))

In [ ]:
prices, prices.shape

(array([10,  8, 12]), (3,))

In [ ]:
Total_sales = prices @ sales_amount
Total_sales

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

In [ ]:
Total_sales = prices @ sales_amount.T
Total_sales

array([240, 138, 458, 232, 142])

In [ ]:
Total_sales.shape

(5,)

---

## **IMPORTANT: 1D Arrays Don't Change Shape in Dot Product**

**Common Confusion:**
- Does `(3,)` convert to `(1, 3)` when doing dot product? **NO!**

**What Actually Happens:**

```
1D Array stays 1D:
prices.shape = (3,)
result = prices @ sales_amount.T
result.shape = (5,)  ← Still 1D! No conversion!

2D Array stays 2D:
prices_2d.shape = (1, 3)
result_2d = prices_2d @ sales_amount.T
result_2d.shape = (1, 5)  ← Still 2D!
```

**The Rule:**
- NumPy **does NOT convert shapes**
- It just **handles the math correctly**
- 1D stays 1D, 2D stays 2D

**In our example:**
```
prices = [10, 8, 12]          shape (3,)
prices @ sales_amount.T       
= [revenue_mon, revenue_tue, revenue_wed, revenue_thu, revenue_fri]
shape (5,) ← 1D output!
```

NumPy is smart about dimensions. No hidden conversions! ✅

---

## **ROWS vs COLUMNS Confusion**

**Visual Example:**
```
Matrix = [[1,  2,  3],
          [4,  5,  6]]

ROWS (horizontal):
  Row 1 = [1, 2, 3]
  Row 2 = [4, 5, 6]

COLUMNS (vertical):
  Col 1 = [1, 4]
  Col 2 = [2, 5]
  Col 3 = [3, 6]

Shape (2, 3) means:
  2 rows
  3 columns
```

---

### **How Rows & Columns Matter in Dot Product**

**Rule:** `(rows1, cols1) @ (rows2, cols2)` ← **cols1 MUST equal rows2**

**Example:**
```
Matrix A: shape (2, 3)  ← 2 rows, 3 columns
Matrix B: shape (3, 5)  ← 3 rows, 5 columns

A @ B works because 3 (cols of A) == 3 (rows of B) ✅

Result: (2, 5)  ← Keep rows from A, keep cols from B
```

---

### **In Our Butter Exercise**

```
prices.shape = (3,)                    ← 3 prices
sales_amount = (5, 3)                  ← 5 days, 3 types per day

We transpose: sales_amount.T = (3, 5)  ← Now 3 rows, 5 columns

prices @ sales_amount.T
(3,) @ (3, 5)
       ↓
   Match! ✅
   
Result: (5,)  ← 5 daily revenues
```

**Why transpose?** We rearranged the data so:
- 3 rows matched 3 prices
- 5 columns gave us 5 days

In [ ]:
butter_prices

       Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [ ]:
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [ ]:
weekly_sales.T

               Mon  Tue  Wed  Thurs  Fri
Almond butter   12    3    9      4    1
Peanut butter   15    3   19      6    6
Cashew butter    0    7   18     12    7

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

       Mon  Tue  Wed  Thurs  Fri
Price  240  138  458    232  142

In [ ]:
daily_sales.T

       Price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [ ]:
daily_sales.shape

(1, 5)

In [ ]:
weekly_sales.shape

(5, 3)

In [ ]:
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
# Doesn't work, not the right shape
weekly_sales["Total ($)"] = daily_sales

ValueError: Columns must be same length as key

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T

In [ ]:
weekly_sales

       Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tue                3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

### **Comparison Operators**

In [33]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
# Element like comparison   
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [35]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [36]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [38]:
type(bool_array),  bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [39]:
a1 > 5

array([False, False, False])

In [ ]:
a1 < 5

array([ True,  True,  True])

In [43]:
a1

array([1, 2, 3])

In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [41]:
a1 == a1

array([ True,  True,  True])

In [45]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [46]:
a1 != a2

array([[False, False,  True],
       [ True,  True,  True]])

## ***Sorting array***