# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [123]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [124]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
               [3, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
               [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [125]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [126]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [127]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [128]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a1, 
                  index=['First', 'Second', 'Third'], 
                  columns= ["Values"])
df

        Values
First        1
Second       2
Third        3

In [129]:
a2

array([[1, 2, 3],
       [3, 5, 6]])

In [130]:
df2 = pd.DataFrame(a2, 
                   index = ["row1", "row2"],
                   columns=["col1", "col2", "col3"])
df2

      col1  col2  col3
row1     1     2     3
row2     3     5     6

In [131]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [132]:
## cause we cant make dataframe out of 3d array must need 2D
a3.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [133]:
df3 = pd.DataFrame(a3.reshape(4, 3))
df3

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [134]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [135]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7, 2, 3))  # 7 -> layer/block, 2 -> 2 rows, 3 -> columns
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [136]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [137]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7,2))
random_array

array([[1, 7],
       [5, 1],
       [4, 0],
       [9, 5],
       [8, 0],
       [9, 2],
       [6, 3]], dtype=int32)

In [138]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_float = np.random.random((3,5))
random_array_float

array([[0.59241457, 0.04645041, 0.60754485, 0.17052412, 0.06505159],
       [0.94888554, 0.96563203, 0.80839735, 0.30461377, 0.09767211],
       [0.68423303, 0.44015249, 0.12203823, 0.49517691, 0.03438852]])

In [139]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array2 = np.random.randint(0, 10, size=(4, 6))
random_array2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [140]:
# # Create an array of random numbers between 1 & 10 of size (3, 7)
# # and save it to a variable
my_arr = np.random.randint(1, 10, size=(3, 7))

# #np.unique() flattens the 2D array into 1D before finding unique values
# #Returns sorted unique values by default
# #Works the same way for any dimension array

# # Find the unique numbers in the array you just created

# unique_array = np.unique(my_arr)
# unique_array

unique_array, count = np.unique(my_arr, return_counts=True)
print(f"Unique numbers: {unique_array}")
print(f"Count: {count}")

Unique numbers: [1 2 3 4 5 7 9]
Count: [1 3 3 3 3 3 5]

In [141]:
# Find the 0'th index of the latest array you created
my_arr, my_arr[0]

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]], dtype=int32),
 array([9, 1, 3, 7, 4, 9, 3], dtype=int32))

In [142]:
my_arr

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]], dtype=int32)

In [143]:
# Get the first 2 rows of latest array you created
my_arr[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [144]:
# Get the first 2 values of the first 2 rows of the latest array
my_arr[:2, :2]

array([[9, 1],
       [5, 3]], dtype=int32)

```text
my_arr[:2, :2]
       ↑    ↑
       │    └─ First 2 COLUMNS (values in each row)
       └────── First 2 ROWS
```

In [145]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

np.random.seed(42)

b1 = np.random.randint(0, 10, size=(3, 5))
b2 = np.ones((3, 5))

b1, b2

(array([[6, 3, 7, 4, 6],
        [9, 2, 6, 7, 4],
        [3, 7, 7, 2, 5]], dtype=int32),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [146]:
# Add the two arrays together
b1 + b2

array([[ 7.,  4.,  8.,  5.,  7.],
       [10.,  3.,  7.,  8.,  5.],
       [ 4.,  8.,  8.,  3.,  6.]])

In [147]:
# Create another array of ones of shape (5, 3)
b3 = np.ones((5,3))
b3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [148]:
# Try add the array of ones and the other most recent array together

# b1 + b3

# ValueError: operands could not be broadcast together with shapes (3,5) (5,3)

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [149]:
b3.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [150]:
# fix

b1 + b3.T

array([[ 7.,  4.,  8.,  5.,  7.],
       [10.,  3.,  7.,  8.,  5.],
       [ 4.,  8.,  8.,  3.,  6.]])

In [151]:
# Create another array of ones of shape (3, 5)
b4 = np.ones((3,5))
b4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [152]:
# Subtract the new array of ones from the other most recent array

b1 - b4, b3.T - b4

(array([[5., 2., 6., 3., 5.],
        [8., 1., 5., 6., 3.],
        [2., 6., 6., 1., 4.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [153]:
# Multiply the ones array with the latest array
b4 * b3.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [154]:
# Take the latest array to the power of 2 using '**'
b1 ** 2

array([[36,  9, 49, 16, 36],
       [81,  4, 36, 49, 16],
       [ 9, 49, 49,  4, 25]], dtype=int32)

In [155]:
# Do the same thing with np.square()
np.square(b1)

array([[36,  9, 49, 16, 36],
       [81,  4, 36, 49, 16],
       [ 9, 49, 49,  4, 25]], dtype=int32)

In [156]:
b1

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]], dtype=int32)

In [157]:
# Find the mean of the latest array using np.mean()
np.mean(b1)

np.float64(5.2)

In [158]:
# Find the maximum of the latest array using np.max()
np.max(b1)

np.int32(9)

In [159]:
# Find the minimum of the latest array using np.min()
np.min(b1)

np.int32(2)

In [160]:
b1

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]], dtype=int32)

In [161]:
# Find the standard deviation of the latest array
np.std(b1)

np.float64(2.039607805437114)

In [162]:
# Find the variance of the latest array
np.var(b1)

np.float64(4.160000000000001)

In [163]:
# Reshape the latest array to (3, 5, 1)
b1, b1.reshape(3, 5, 1)

(array([[6, 3, 7, 4, 6],
        [9, 2, 6, 7, 4],
        [3, 7, 7, 2, 5]], dtype=int32),
 array([[[6],
         [3],
         [7],
         [4],
         [6]],

        [[9],
         [2],
         [6],
         [7],
         [4]],

        [[3],
         [7],
         [7],
         [2],
         [5]]], dtype=int32))

In [164]:
# Transpose the latest array
b1.T

array([[6, 9, 3],
       [3, 2, 7],
       [7, 6, 7],
       [4, 7, 2],
       [6, 4, 5]], dtype=int32)

What does the transpose do?

In [165]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

rand1 = np.random.randint(0, 10, size=(3, 3))
rand2 = np.random.randint(0, 10, size=(3,2))

rand1, rand1.shape, rand2, rand2.shape

(array([[4, 1, 7],
        [5, 1, 4],
        [0, 9, 5]], dtype=int32),
 (3, 3),
 array([[8, 0],
        [9, 2],
        [6, 3]], dtype=int32),
 (3, 2))

In [166]:
# Perform a dot product on the two newest arrays you created
rand1 @ rand2

array([[ 83,  23],
       [ 73,  14],
       [111,  33]], dtype=int32)

In [167]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(42)

random1 = np.random.randint(0, 10, size=(4, 3))
random2 = np.random.randint(0, 10, size=(4, 3))

random1, random1.shape, random2, random2.shape

(array([[6, 3, 7],
        [4, 6, 9],
        [2, 6, 7],
        [4, 3, 7]], dtype=int32),
 (4, 3),
 array([[7, 2, 5],
        [4, 1, 7],
        [5, 1, 4],
        [0, 9, 5]], dtype=int32),
 (4, 3))

In [168]:
# Perform a dot product on the two newest arrays you 

#random1 @ random2

# ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

It doesn't work. How would you fix it?

In [169]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

random1 @ random2.T

array([[83, 76, 61, 62],
       [85, 85, 62, 99],
       [61, 63, 44, 89],
       [69, 68, 51, 62]], dtype=int32)

In [170]:
np.dot(random1, random2.T)

array([[83, 76, 61, 62],
       [85, 85, 62, 99],
       [61, 63, 44, 89],
       [69, 68, 51, 62]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [171]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

np.random.seed(42)

a1 = np.random.randint(0, 10, size=(2, 4))
a2 = np.random.randint(0, 10, size=(2, 4))

a1, a2

(array([[6, 3, 7, 4],
        [6, 9, 2, 6]], dtype=int32),
 array([[7, 4, 3, 7],
        [7, 2, 5, 4]], dtype=int32))

In [172]:
# Compare the two arrays with '>'
a1 > a2

array([[False, False,  True, False],
       [False,  True, False,  True]])

What happens when you compare the arrays with `>`?

In [173]:
# Compare the two arrays with '>='

a1 >= a2

array([[False, False,  True, False],
       [False,  True, False,  True]])

In [174]:
a1

array([[6, 3, 7, 4],
       [6, 9, 2, 6]], dtype=int32)

In [175]:
# Find which elements of the first array are greater than 7

a1 > 7

array([[False, False, False, False],
       [False,  True, False, False]])

In [176]:
# Which parts of each array are equal? (try using '==')

a1 == a2

array([[False, False, False, False],
       [False, False, False, False]])

In [177]:
a1

array([[6, 3, 7, 4],
       [6, 9, 2, 6]], dtype=int32)

In [178]:
# Sort one of the arrays you just created in ascending order

np.sort(a1)

array([[3, 4, 6, 7],
       [2, 6, 6, 9]], dtype=int32)

In [179]:
# Sort the indexes of one of the arrays you just created

np.argsort(a1)

array([[1, 3, 0, 2],
       [2, 0, 3, 1]])

In [180]:
a1

array([[6, 3, 7, 4],
       [6, 9, 2, 6]], dtype=int32)

In [184]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

np.int64(5)

In [186]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1)

np.int64(6)

In [187]:
a1

array([[6, 3, 7, 4],
       [6, 9, 2, 6]], dtype=int32)

In [188]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(a1, axis=1)

array([2, 1])

In [190]:
a1

array([[6, 3, 7, 4],
       [6, 9, 2, 6]], dtype=int32)

In [189]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmax(a1, axis=0)

array([0, 1, 0, 1])

In [193]:
# Create an array of normally distributed random numbers
normal_random = np.random.randn(2, 3)
normal_random

array([[ 0.81644508, -1.523876  , -0.42804606],
       [-0.74240684, -0.7033438 , -2.13962066]])

In [194]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaces_array= np.linspace(1, 100, 10)
evenly_spaces_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.